example/js/LabelsExample.jsx
example/js/Layout.jsx
lib/Label.jsx
lib/index.js
test/Label.spec.js

The bs4 label component has no sizing options. The size depends on the parent, ese.
Fixes #3

Issue 3 add component labels

---

.travis.yml
example/js/Layout.jsx
example/js/ModalExample.jsx
lib/Fade.jsx
lib/Modal.jsx
lib/ModalBody.jsx
lib/ModalFooter.jsx
lib/ModalHeader.jsx
lib/index.js
test/Fade.spec.js
test/Modal.spec.js
test/ModalBody.spec.js
test/ModalFooter.spec.js
test/ModalHeader.spec.js

First run at applying fade classes to a component. Modal has a fade in for backdrop and modal content. Added a Fade component to help with toggling classes from `.fade` to `.fade.in` via state.
Modal Props
- isOpen
- toggle
- onExit - called after exit
- onEnter - called after enter
Modal Header Props
- toggle - adding this enables close button

Modal Component

---

docs/lib/Components/ButtonsPage.jsx
lib/Button.jsx
lib/Dropdown.jsx
lib/DropdownItem.jsx
test/Button.spec.js
test/DropdownItem.spec.js

BREAKING CHANGE: `El` prop is now `tag`. This standardizes the way
custom elements should render their html “tags”.

refactor(components): standardize custom tag names

---

CHANGELOG.md
package.json

includes correct external dependency for react-addons-transition-group (instead of css-transition-group)

chore(release): adding 1.3.3

---

docs/lib/Home/index.jsx
docs/lib/NotFound/index.jsx
docs/lib/examples/ButtonOutline.jsx
docs/lib/examples/CardOutline.jsx
src/Button.jsx
src/Card.jsx
test/Button.spec.js
test/Card.spec.js

The outline for buttons and cards is now it's own props separate from the color value.
Based on https://github.com/reactstrap/reactstrap/issues/33#issuecomment-214025488
This also adds additional tests around this new props.
Also:
Cards, unlike buttons, do not have a default color. Thus adding outline prop to a card without a color will do nothing.
Is this acceptable? Should it produce a warning/error? Should it default to 'card-outline-secondary' when outline is provided but no color is provided?

feat(outline): Make outline a separate prop

---

webpack.dev.config.js

When running localhost / dev webpack, the tags route cannot be navigated to directly (or reloaded). This is because I missed a reference when updating labels to tags. This PR fixes that.

fix(docs): update path to allow direct loading of the tags doc page

---

docs/lib/Components/FormPage.jsx
docs/lib/Components/index.jsx
docs/lib/examples/Form.jsx
docs/lib/examples/FormFeedback.jsx
docs/lib/examples/FormGrid.jsx
docs/lib/examples/FormInline.jsx
docs/lib/examples/InputGridSizing.jsx
docs/lib/examples/InputSizing.jsx
docs/lib/examples/InputType.jsx
docs/lib/examples/LabelHidden.jsx
docs/lib/routes.jsx
docs/static/docs.css
src/Form.jsx
src/FormFeedback.jsx
src/FormGroup.jsx
src/FormText.jsx
src/Input.jsx
src/Label.jsx
src/index.js
test/Form.spec.js
test/FormFeedback.spec.js
test/FormGroup.spec.js
test/FormText.spec.js
test/Input.spec.js
test/Label.spec.js
webpack.dev.config.js

#50 
Forms and form element components as well as docs and tests including:
- Form
- FormGroup
- FormFeedback
- FormText
- Input
- Label
What this **doesn't** include for forms:
- [input-group and input-group-addon](http://v4-alpha.getbootstrap.com/components/forms/#hidden-labels)
- something about grouping [radio and checks](http://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios) (this seems like something twbs is changing in v4 (new `.form-check` vs `.radio` and `.check`) half of their docs use or the other)
- [custom forms](http://v4-alpha.getbootstrap.com/components/forms/#custom-forms) (Is this new to bs4, don't think I have seen this before)
- fieldsets (doesn't seem like it would be useful since everything would just pass right though `<Fieldset disabled>` -> …

feat(form): add forms and form element components

---

docs/lib/Components/ButtonDropdownPage.jsx
docs/lib/examples/ButtonDropdownMultiSplit.jsx
src/DropdownToggle.jsx
test/DropdownToggle.spec.js

Minor fix for split dropdown. The padding around the caret should be smaller. We can make this adjustment using the `dropdown-toggle-split` class.

feat(Dropdowns): use split class for split dropdowns

---

docs/lib/examples/CardContentTypes.jsx
src/CardImg.jsx

Minor fix for card image border radius.
Note that a card image should have one of `card-img`, `card-img-top`, or `card-img-bottom` (this is a Bootstrap inconsistency).
Also, when a card image is in the middle of a card, a plain image is used in the Bootstrap example. We may still want to use CardImg here, but ensure no classes are applied.

feat(Card): fix image class

---

src/Modal.jsx

Currently the size property of `Modal` does nothing. This adds modal-size to the className if a size is specified.

Make sure size property of modal has effect.

---

CHANGELOG.md
package.json

<a name="2.2.0"></a>
* **Card:** update img position classes ([#91](https://github.com/reactstrap/reactstrap/issues/91)) ([920e2f8](https://github.com/reactstrap/reactstrap/commit/920e2f8))
* **Dropdown:** add size prop ([#90](https://github.com/reactstrap/reactstrap/issues/90)) ([92c62b1](https://github.com/reactstrap/reactstrap/commit/92c62b1))
* **Dropdowns:** use split class for split dropdowns ([#92](https://github.com/reactstrap/reactstrap/issues/92)) ([ee17a47](https://github.com/reactstrap/reactstrap/commit/ee17a47))

chore(release): adding 2.2.0

---

test/Modal.spec.js

Fixes code branch coverage not testing 100%. Size tests were missing from #95.
Turns this:
into this:
(now all 100%)

fix(tests): fix coverage for Modal tests

---

docs/lib/Components/InputGroupPage.jsx
docs/lib/Components/index.jsx
docs/lib/examples/InputGroupAddon.jsx
docs/lib/examples/InputGroupButton.jsx
docs/lib/examples/InputGroupButtonShorthand.jsx
docs/lib/examples/InputGroupOverview.jsx
docs/lib/examples/InputGroupSizing.jsx
docs/lib/routes.jsx
src/Input.jsx
src/InputGroup.jsx
src/InputGroupAddon.jsx
src/InputGroupButton.jsx
src/index.js
test/Input.spec.js
test/InputGroup.spec.js
test/InputGroupAddon.spec.js
test/InputGroupButton.spec.js
webpack.dev.config.js

Resolves #74
Add `InputGroup` with `size` prop
Add `InputGroupAddon`
Change Input to add `addon` prop for radio/checkbox to not add `form-check-input` class
Add `InputGroupButton` with convinence shorthand when only a single string is passed
Add tests for all of the above
Add documention

feat(inputGroup): add InputGroup

---

.babelrc
package.json
webpack.test.config.js

Replace isparta with istambul since isparta is no longer maintained
See: https://github.com/douglasduteil/isparta
Istambul now support es2015/6.
(Also added cross-env to allow it to work on windows)
This PR is not a big deal, just some maintenance, though I did notice the coverage output was _slightly_ more detailed with the babel istambul plugin this PR adds than the isparta loader it replaces.

chore(coverage): Update instrumenter

---

docs/lib/Components/MediaPage.jsx
docs/lib/Components/index.jsx
docs/lib/app.jsx
docs/lib/examples/Media.jsx
docs/lib/examples/MediaAlignment.jsx
docs/lib/examples/MediaList.jsx
docs/lib/examples/MediaNested.jsx
docs/lib/routes.jsx
package.json
src/Media.jsx
src/index.js
test/Media.spec.js
webpack.dev.config.js

References #75
Notes
- The media components are fairly lightweight (almost single class). This is particularly true for `MediaHeading` and `MediaObject`.
- I'm using `MediaMarginal` for shared code between `MediaLeft` and `MediaRight`. It's not intended for direct use by users, but is exposed so we can test it.
- In `MediaList`, I'm applying `tag="li"` to the children. This way, the user of `MediaList` doesn't have to specify `li` on each `Media` item.
- I'm using [Holder](http://holderjs.com) to populate placeholder images, similar to the Bootstrap docs. Also, I had to rerun Holder on route update. Without this, if the user goes to `/components/media`, then `/components/buttons`, then hits back, the placeholder image isn't populated.

feat(Media): add component

---

docs/lib/Components/ProgressPage.jsx
docs/lib/Components/index.jsx
docs/lib/examples/Progress.jsx
docs/lib/examples/ProgressAnimated.jsx
docs/lib/examples/ProgressColor.jsx
docs/lib/examples/ProgressMax.jsx
docs/lib/examples/ProgressStriped.jsx
docs/lib/routes.jsx
package.json
src/Progress.jsx
src/index.js
test/Progress.spec.js
webpack.dev.config.js

Add Progress component which will output bootstrap's progress component
Progress has `striped`, `animated`, and `color` props.
It will default to `<progress>` with a `<div>` fallback for IE9
Overriding the tag will produce the fallback inside the custom tag.
Add docs and tests as well.
Closes #78

feat(Progress): add Progress component

---

src/Modal.jsx

Hello,
I was having some issues with controlled inputs inside modals. When I would update the Modal after an input value changed, the input would suddenly lose focus. I managed to track this issue down to the Modal's focus state being set after the call to `renderIntoSubtree()`. This meant that the Modal wasn't be focused until the next render, when the input changed values.
Here is some React code to show what I mean:
```jsx
import React from "react";
import {Modal,ModalBody} from "reactstrap";
class ModalWithInput extends React.Component {
state = {};
render() {
return <Modal {...this.props}>
<ModalBody>
<input
type="text"
value={this.state.inputValue}
onChange={(e) => this.setState({ inputValue: e.target.value })} />
</ModalBody>
</Modal>;
}
}
```

set modal focus state before showing

---

CHANGELOG.md
package.json

<a name="2.5.0"></a>
* **Modal:** set focus state before showing ([#104](https://github.com/reactstrap/reactstrap/issues/104)) ([a358233](https://github.com/reactstrap/reactstrap/commit/a358233))
* **Modal:** use togglePortal on componentDidMount ([#106](https://github.com/reactstrap/reactstrap/issues/106)) ([942b24a](https://github.com/reactstrap/reactstrap/commit/942b24a))
* **Progress:** add Progress component ([#105](https://github.com/reactstrap/reactstrap/issues/105)) ([bc185d8](https://github.com/reactstrap/reactstrap/commit/bc185d8)), closes [#78](https://github.com/reactstrap/reactstrap/issues/78)

chore(release): adding 2.5.0

---

docs/lib/Components/ModalsPage.jsx
docs/lib/examples/Modal.jsx
src/Modal.jsx
test/Modal.spec.js
webpack.base.config.js

Related Issue: #110
- Users should be able to style modals and should be able to namespace the same.
- This will help us have styling specific for modals and the rest be generic.

feat(ModalClassName): Adds custom class name for modal-dialogs

---

CHANGELOG.md
package.json

<a name="2.6.1"></a>
* **ModalClassName:** Adds custom class name for modal-dialogs for namespacing ([#111](https://github.com/reactstrap/reactstrap/issues/111)) ([5f7cab6](https://github.com/reactstrap/reactstrap/commit/5f7cab6))

chore(release): adding 2.6.1

---

docs/lib/Components/ButtonDropdownPage.js
docs/lib/Components/ButtonGroupPage.js
docs/lib/Components/ButtonsPage.js
docs/lib/Components/DropdownsPage.js
docs/lib/examples/ButtonDropdownMultiSplit.js
src/Button.js
src/DropdownToggle.js
test/Button.spec.js
test/DropdownToggle.spec.js

This fixes some inconsistencies within button and dropdown components and removes some weird behavior found in #98.
- Button color defaults to `secondary` (previously default style in bs3)
- DropdownToggle: no longer clones each element in props.children when it’s an array, instead it renders props.children inside a single component (Button) with the onClick toggle context.

Button & DropdownToggle updates

---

CHANGELOG.md
package.json

<a name="3.0.0"></a>
* **Button,DropdownToggle:** default to secondary style, remove cloning ([#120](https://github.com/reactstrap/reactstrap/issues/120)) ([5c56749](https://github.com/reactstrap/reactstrap/commit/5c56749)), closes [#98](https://github.com/reactstrap/reactstrap/issues/98)
* Button,DropdownToggle: DropdownToggle no longer clones each element in props.children when it’s an array, instead it renders props.children inside a single component (Butt
* Button,DropdownToggle: Button color now defaults to “secondary”. This behavior aligns with DropdownToggle color default.
See #120 for more information regarding the change.

chore(release): adding 3.0.0

---

src/TetherContent.js
test/TetherContent.spec.js

Fix #125
Let the TetherContent re-render when any props change while it is
showing. This allows the children to update dynamically without
needing to hide and show the content to force the update.
This also includes tests, but no additional docs as this is not a feature, but something that should just work this way.
If you would like me to add to the docs to document this, let me know and I will adjust this PR.

fix(TetherContent): rerender when other props change

---

src/Modal.js

Fixes #126
Change the event listeners for click and keyup in modal
to set `useCapture` to true to trigger the handler before
any other handler.

fix(modal): fix event listener for modal

---

CHANGELOG.md
package.json

<a name="3.0.1"></a>
* **docs:** update deploy script ([8fd0761](https://github.com/reactstrap/reactstrap/commit/8fd0761))
* **modal:** fix event listener for modal ([#127](https://github.com/reactstrap/reactstrap/issues/127)) ([c778608](https://github.com/reactstrap/reactstrap/commit/c778608)), closes [#126](https://github.com/reactstrap/reactstrap/issues/126)
* **TetherContent:** rerender when other props change ([#128](https://github.com/reactstrap/reactstrap/issues/128)) ([25600d4](https://github.com/reactstrap/reactstrap/commit/25600d4)), closes [#125](https://github.com/reactstrap/reactstrap/issues/125)

chore(release): adding 3.0.1

---

docs/lib/Components/ModalsPage.js
docs/lib/examples/ModalBackdrop.js
src/Modal.js
src/TabContent.js
test/Modal.spec.js

Closes #134
Add backdrop prop to modal with the following options
- `true` show backdrop, close on click (default)
- `false` hide backdrop
- `"static"` show backdrop, do not close on click
Add keyboard prop to modal with the following options
- `true` close on escape (default)
- `false` do not close on escape
Add tests and docs

feat(modal): add backdrop and keyboard options

---

src/Modal.js
test/Modal.spec.js

Resolves #137
Moves the click and keyup listeners from the document to the
`.modal` div, which wraps the modal-dialog. This allows for each
modal to be individually triggered to close.

feat(Modal): allow for multiple modals

---

src/TabContent.js
test/Tabs.spec.js

Adds additional test to bring coverage back up to 100%
Also, just throwing this in here. I do not like the way the tests were written for the Tab components. Testing is supposed to improve code confidence, but I do not feel these tests did that for me.

fix(TabContent): fix TabContent test coverage

---

docs/lib/Components/TooltipsPage.js
src/Tooltip.js
test/Tooltip.spec.js

Previous delay was a harcoded value of 250ms for the *hide*, and no delay for the
*show*.
New prop `delay` allows for either an object of form:
`{ show: 100, hide: 200 }` or simply a number to set these delays.
Default is `{ show: 0, hide: 250 }`
Closes #115

feat: add delay prop to Tooltip

---

CHANGELOG.md
package.json

<a name="3.2.1"></a>
* **Tooltip:** add delay prop ([#143](https://github.com/reactstrap/reactstrap/issues/143)) ([b18fb74](https://github.com/reactstrap/reactstrap/commit/b18fb74)), closes [#115](https://github.com/reactstrap/reactstrap/issues/115)

chore(release): adding 3.2.1

---

docs/lib/Components/TooltipsPage.js
docs/lib/examples/TooltipAutoHide.js
src/Tooltip.js
test/Tooltip.spec.js

Adds autohide prop to tooltip. When autohide is false, hovering over tooltip content will not close the tooltip.
example use case: UI needs to allow users a chance to copy content from tooltip content.

Tooltip autohide prop

---

test/Tabs.spec.js

- Removes `<TabsExample />` (which requires no test) and mocks everything possible.
- Tests TabContent & TabPane components alone and nothing else.
@TheSharpieOne Let me know if I misunderstood anything wrong from yesterday. Will be happy to fix it.

fix(TabContent,TabPane): Fixes TabContent & Tabpane tests

---

CHANGELOG.md
package.json

<a name="3.3.0"></a>
* **Jumbotron:** add Jumbotron Component ([#151](https://github.com/reactstrap/reactstrap/issues/151)) ([20f9c03](https://github.com/reactstrap/reactstrap/commit/20f9c03)), closes [#73](https://github.com/reactstrap/reactstrap/issues/73)

chore(release): adding 3.3.0

---

src/Label.js
src/__tests__/Label.spec.js

Adds the disabled class when the label has both the inline and
check props. This is the way bootstrap disables inline radio
and checkboxes since there is no wrapping element.
I must have missed this use-case before when creating the forms and labels. The whole form-check classes are new to bootstrap 4.
Note: there is currently an open issue with bootstrap (twbs/bootstrap#20799) to correct the color of the disabled label's text (and to clarify how to denote disabled inline radio/checkboxes in the docs as it is not there, I had to infer it from [the styles](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.4/scss/_forms.scss#L241-L243))

fix(label): add disabled class when form-check-inline and disabled

---

CHANGELOG.md
package.json

<a name="3.3.1"></a>
* **label:** add disabled class when form-check-inline and disabled ([#159](https://github.com/reactstrap/reactstrap/issues/159)) ([312b29e](https://github.com/reactstrap/reactstrap/commit/312b29e))

chore(release): adding 3.3.1

---

src/Modal.js
src/__tests__/utils.spec.js
src/utils.js

Currently, body and fixed navbars get pushed because of the modal-open class. This pr only fixes the regular body content. Need to look at how bootstrap does this for the [fixed content](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.4/js/src/modal.js#L70).
Fixes part of #164.
Need to look at [adjusting](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.4/js/src/modal.js#L395-L406) modal dialog as well. 
Also I had a hard time getting tests in for this. Going leave those commented out for now.

fix(Modal): Account for body padding when scrollbar is present

---

CHANGELOG.md
package.json

<a name="3.3.2"></a>
* **Modal:** Account for body padding when scrollbar is present ([#165](https://github.com/reactstrap/reactstrap/issues/165)) ([e159628](https://github.com/reactstrap/reactstrap/commit/e159628))

chore(release): adding 3.3.2

---

docs/lib/Components/AlertPage.js
docs/lib/Components/AlertsPage.js
docs/lib/Components/index.js
docs/lib/Home/index.js
docs/lib/examples/Alert.js
docs/lib/examples/AlertDismiss.js
docs/lib/routes.js
package.json
src/Alert.js
src/__tests__/Alert.spec.js
src/index.js
webpack.dev.config.js

Hello! I was working on a small project using reactstrap, made an alert, and thought it would be cool to clean things up and make a PR.  In summary, this simply adds a Bootstrap 4 alert, and a documentation page with some examples.
I would like to note a few things for discussion, in addition to any comments or suggestions you might have!
- I've added a peer dependency on `react-addons-css-transition-group`.  It wasn't my favorite thing to do; however, it made implementing the dismissible fade-out easier.
- I didn't know the order for the documentation pages, so I've added it to the end.
- Should there be a link to the Bootstrap docs describing how to use `.alert-heading` and `.alert-link`?  I only ask to maintain some feature parity with Bootstrap 4.
- In issue #6, there props outlined …

Add Alert Component

---

docs/lib/Components/index.js

Change menu item incorrectly spelled as "Breadscrumbs" to the correct form "Breadcrumbs".

docs(components): fix typo in components page menu

---

src/Input.js

PR enables refs on Input components. I think it’s fairly common to want to add a ref to an input for doing blur/focus or other events on the dom element.
Info can be found here: https://facebook.github.io/react/docs/more-about-refs.html#cautions
> Refs may not be attached to a stateless function, because the component does not have a backing instance. You can always wrap a stateless component in a standard composite component and attach a ref to the composite component.
Related to #172

feat(Input): enable refs on Input components

---

CHANGELOG.md
package.json

<a name="3.4.1"></a>
* **Input:** enable refs on Input components ([#178](https://github.com/reactstrap/reactstrap/issues/178)) ([ed9e584](https://github.com/reactstrap/reactstrap/commit/ed9e584))

chore(release): adding 3.4.1

---

docs/lib/Components/LayoutPage.js
docs/lib/examples/Layout.js
src/Col.js
src/__tests__/Col.spec.js

Hi!
As requested in issue #169 I implemented support for dropping the size for the Col component, respectively flexbox support.
I added support for all suggestions by @eddywashere, meaning a value can be dropped at all, or set to "flex" and "auto", like:
```html
<Col xs />
<Col xs="auto" />
<Col xs="flex" />
<Col
xs={{ size: true, push: 2, pull: 2, offset: 2 }}
sm={{ size: 'auto', push: 2, pull: 2, offset: 2 }}
md={{ size: 'flex', push: 2, pull: 2, offset: 2 }}
/>
```
If the object's size shall accept boolean as well, and both "flex" and "auto" should be supported may needs some discussion?
Corresponding unit tests were added as well.
Looking forward to your feedback
Ronny

Add flex-support for Col component #169

---

src/Tooltip.js
src/__tests__/Tooltip.spec.js

Before, when props.toggle was not provided, this.toggle would throw
Essentially when someone just provides the `isOpen` prop and wants
to manually control the hiding/showing.
`onMouseOverTooltip` would trigger `show`, which would trigger `toggle` when the tooltip was not being shown. Without `toggle` prop, it would error.

fix(tooltip): fix when toggle is not provided

---

CHANGELOG.md
package.json

<a name="3.5.0"></a>
* **Tooltip:** fix when toggle is not provided ([#182](https://github.com/reactstrap/reactstrap/issues/182)) ([47239f3](https://github.com/reactstrap/reactstrap/commit/47239f3))
* **Col:** add flex-support to Col component ([#169](https://github.com/reactstrap/reactstrap/issues/169)) ([#175](https://github.com/reactstrap/reactstrap/issues/175)) ([ebdecb8](https://github.com/reactstrap/reactstrap/commit/ebdecb8))
* **Popover:** add `tetherRef` to Popover ([#183](https://github.com/reactstrap/reactstrap/issues/183)) ([00d08ad](https://github.com/reactstrap/reactstrap/commit/00d08ad))
* **TetherContent:** Add `tetherRef` to TetherContent  ([#181](https://github.com/reactstrap/reactstrap/issues/181)) ([6be1a67](https://github.com/reactstrap/reactstrap/commit/6be1a67)), …

chore(release): adding 3.5.0

---

docs/lib/Components/ButtonsPage.js
docs/lib/examples/Button.js
docs/lib/examples/ButtonGroup.js
docs/lib/examples/ButtonOutline.js
docs/lib/examples/TagPills.js
docs/static/docs.css

This removes the special button margin which is in the docs and
replaces it with `{' '}` to add an actual space in the HTML markup.
This makes the button spacing work like bootstrap does and documents
`{' '}` being used.
I am addressing this because I feel that it should be addressed. I have seen many developers not have spacing between buttons because they followed/copy&paste the docs here (which did not have a space, only special css) and it makes it look bad. Bootstrap intended there to be a space separating the buttons. Documenting the space saves headaches and prevents users from adding special CSS to add the space... and not have the space in some places (such as the CSS the docs were using)

chore(docs): button spacing

---

docs/lib/examples/NavPills.js
docs/lib/examples/NavTabs.js

Noticed an issue where the dropdown in nav (pills and tabs) were looking weird. It turns out it was using incorrect markup. Instead of nesting nav-link in the dropdown toggle, it should be combined. I’m not sure if this was part of alpha v5, or if the markup and classes were always off.
I’m hesitant to add a new component to simplify this or to add a prop to DropdownToggle to enable this common usage. For now, I’m updating the docs to use the built in flexibility of the existing dropdown toggle component.

docs(Navs): Update nav dropdown markup

---

docs/lib/Components/DropdownsPage.js
docs/lib/examples/NavPills.js
docs/lib/examples/NavTabs.js
src/DropdownToggle.js
src/__tests__/DropdownToggle.spec.js

Follow up to #196. Decided to go with prop to simplify adding a DropdownToggle inside a Nav. There were drawbacks to using what I documented previously in #196, most around losing out on Button prop support when switching from Button to NavLink in the wrapping element for this component. By using a prop, the Button is still used, and Button props can be passed along, like color/size/etc.

feat(DropdownToggle): add nav prop to enable Nav specific functionality

---

CHANGELOG.md
package.json

<a name="3.6.0"></a>
* **DropdownToggle:** add nav prop to enable Nav specific functionality ([#197](https://github.com/reactstrap/reactstrap/issues/197))([9b28cbc](https://github.com/reactstrap/reactstrap/commit/9b28cbc))

chore(release): adding 3.6.0

---

docs/lib/Components/ButtonDropdownPage.js
docs/lib/Components/ButtonGroupPage.js
docs/lib/Components/DropdownsPage.js
docs/lib/Components/index.js
docs/lib/Home/index.js
docs/lib/NotFound/index.js
docs/lib/UI/Nav.js
docs/lib/examples/Jumbotron.js
docs/lib/examples/MediaAlignment.js
docs/lib/examples/Navbar.js
docs/lib/examples/PopoverMulti.js
docs/lib/examples/TooltipMulti.js

I noticed the docs were slightly off... A few things changed from BS4a4 to BS4a5 around utilities.
Spacers dropped the first hyphen (e.g. `p-t-2` -> `pt-2`)
Pulls are now floats (e.g. `pull-xs-right` -> `float-xs-right`)

docs(*): fix class changes from bs4a4 to bs4a5

---

src/Dropdown.js
src/TetherContent.js
src/Tooltip.js

Similar to a previous issue where an event was triggered AFTER some DOM manipulation which caused the event logic to run after things changed. This really only impacted when the thing that triggered the event was no longer in the DOM which changed the flow and triggered things to happen.
It is probably best to _globally_ do the same thing, which is to handle the event as soon as possible using `useCapture`.

fix(events): use capture events

---

CHANGELOG.md
package.json

<a name="3.7.0"></a>
* **events:** add useCapture to events attached to document ([#202](https://github.com/reactstrap/reactstrap/issues/202)) ([18d7d04](https://github.com/reactstrap/reactstrap/commit/18d7d04))
* **cssModule:** add support for css module ([#206](https://github.com/reactstrap/reactstrap/issues/206)) ([3a69f14](https://github.com/reactstrap/reactstrap/commit/3a69f14)), closes [#205](https://github.com/reactstrap/reactstrap/issues/205)

chore(release): adding 3.7.0

---

.travis.yml
src/Alert.js
src/Dropdown.js
src/Fade.js
src/Popover.js
src/Progress.js
src/__tests__/TetherContent.spec.js

There were a few existing eslint errors, mostly around import order. I've fixed those, then set up Travis to run `npm run lint` after the tests to avoid these in the future.

Fix eslint errors, add lint to Travis checks.

---

CHANGELOG.md
package.json

<a name="3.7.1"></a>
* **NavbarToggler:** remove unnecessary menu char ([#200](https://github.com/reactstrap/reactstrap/issues/200)) ([67544a3](https://github.com/reactstrap/reactstrap/commit/67544a3))

chore(release): adding 3.7.1

---

src/Button.js
src/CardLink.js
src/Form.js
src/Input.js
src/NavLink.js

The main use-case for refs is the ability to set focus on an element, because of this, I have added the ability to get a ref to components which generate focusable items (inputs, buttons, links/anchor).
I just want to note, using a ref to get an input's value is not the correct way. Using a callback, such `onChange` or `onBlur`, you can use the supplied event to get the value without needing a ref.

feat(*): add way to get ref to focuable components

---

CHANGELOG.md
package.json

<a name="3.8.1"></a>
* **refs:** add getRef to focusable components ([#218](https://github.com/reactstrap/reactstrap/issues/218)) ([cbfa0e0](https://github.com/reactstrap/reactstrap/commit/cbfa0e0))

chore(release): adding 3.8.1

---

src/DropdownToggle.js
src/__tests__/DropdownToggle.spec.js

Supersedes #220 
This is one of those interesting 'defaults' which in the case of `nav`, it would tell the Button to become an anchor tag, but if the tag was already being override via DropdownToggle's `tag` prop, it would try to set the `tag` prop on that thing, which may not support the `tag` prop.

fix(DropdownToggle): only set tag prop if the Tag is default button

---

CHANGELOG.md
package.json

<a name="3.9.1"></a>
* **modal:** fix multi-modal backdrop ([#227](https://github.com/reactstrap/reactstrap/issues/227)) ([9ddeb8a](https://github.com/reactstrap/reactstrap/commit/9ddeb8a)), closes [#222](https://github.com/reactstrap/reactstrap/issues/222)

chore(release): adding 3.9.1

---

CHANGELOG.md
package.json

<a name="3.9.2"></a>
* **Popover:** remove old arrow markup, correct enabled className ([b9d3ea7](https://github.com/reactstrap/reactstrap/commit/b9d3ea7))
* **TetherContent:** Fixes className prop typo, removes arrow & position relative hack ([d9e7621](https://github.com/reactstrap/reactstrap/commit/d9e7621))
* **Tooltip:** remove old arrow markup, correct enabled className ([62d622b](https://github.com/reactstrap/reactstrap/commit/62d622b))

chore(release): adding 3.9.2

---

CHANGELOG.md
package.json

<a name="4.0.0-alpha.2"></a>
* **className:** update "in" to "active" for stateful components ([#241](https://github.com/reactstrap/reactstrap/issues/241)) ([ea2439e](https://github.com/reactstrap/reactstrap/commit/ea2439e))

chore(release): adding 4.0.0-alpha.2

---

docs/lib/Components/ListGroupPage.js
docs/lib/Components/index.js
docs/lib/examples/ListGroup.js
docs/lib/examples/ListGroupAnchorsAndButtons.js
docs/lib/examples/ListGroupContextualClasses.js
docs/lib/examples/ListGroupCustomContent.js
docs/lib/examples/ListGroupDisabledItems.js
docs/lib/examples/ListGroupTag.js
docs/lib/routes.js
src/ListGroupItem.js
src/__tests__/ListGroupItem.spec.js
webpack.dev.config.js

#185  Add ListGroup doc.
**API Change in ListGroupItem component:**
When I write doc, I found that using `color="success"` to set contextual class is not a good idea.
The `color` prop is no longer support, when you want to set a contextual class, just pass the name (one of “success”, “info”, “warning”, “danger”) to the component.
Since this component is not exists in doc yet and just released a few days, I think the change is acceptable.

ListGroup doc #185

---

src/Fade.js

- Not sure if this is the entire fix. But this fixed the error related to this issue (https://github.com/facebook/react/issues/5240).
- A similar issue fixed in React (https://github.com/facebook/react/pull/5391/files) & MaterialUI (https://github.com/callemall/material-ui/pull/3437) ( [source](https://github.com/callemall/material-ui/commit/38d5d3ef917893b6c21a98887c1ef085765e93ee))
Fixes: https://github.com/reactstrap/reactstrap/issues/166

Fixes rapid opening and closing of modal (Fade component fix) #166 

---

CHANGELOG.md
package.json

<a name="3.9.4"></a>
* **Modal:** clear timeouts when toggling of modal - [#166](https://github.com/reactstrap/reactstrap/issues/166) ([5e0f5d2](https://github.com/reactstrap/reactstrap/commit/5e0f5d2))

chore(release): adding 3.9.4

---

CHANGELOG.md
package.json

<a name="4.0.0-alpha.4"></a>
* **Modal:** clear timeouts when toggling of modal - [#166](https://github.com/reactstrap/reactstrap/issues/166) ([5e0f5d2](https://github.com/reactstrap/reactstrap/commit/5e0f5d2))

chore(release): adding 4.0.0-alpha.4

---

src/Modal.js

Currently it's not possible to for example change the size (excluding default Bootstrap sizes) of modals. This change allows users to style the modal dialog.

Pass through unused props in Modal

---

CHANGELOG.md
package.json

<a name="3.9.5"></a>
* **Modal:** Pass through props in Modal ([#254](https://github.com/reactstrap/reactstrap/issues/254)) ([a783308](https://github.com/reactstrap/reactstrap/commit/a783308))

chore(release): adding 3.9.5

---

CHANGELOG.md
package.json

<a name="4.0.0-alpha.5"></a>
* **Modal:** Pass through props in Modal ([#254](https://github.com/reactstrap/reactstrap/issues/254)) ([c99e873](https://github.com/reactstrap/reactstrap/commit/c99e873))

chore(release): adding 4.0.0-alpha.5

---

docs/lib/Components/LayoutPage.js
docs/lib/examples/Layout.js
package.json
src/Col.js
src/__tests__/Col.spec.js

BREAKING CHANGE: The default xs prop now returns `.col` instead of
`.col-xs-12`. The `auto` size value now returns `.col-auto` or
`.col-sm-auto` for variable width content columns. Use `true` or `''`
as the size value to return `.col` or `.col-sm` for auto layout of
columns (not to be confused with `auto`  -> (variable width of
content)).
Holding off on the flex utility props. I'm starting to think that would be too much and people should apply flex utility classes via className.

feat(Col): update classes based on alpha.6 changes

---

CHANGELOG.md
package.json

<a name="4.0.0-alpha.7"></a>
* **Col:** update classes based on alpha.6 changes ([#267](https://github.com/reactstrap/reactstrap/issues/267)) ([89ff16c](https://github.com/reactstrap/reactstrap/commit/89ff16c))
* **Collapse:** add navbar prop ([#266](https://github.com/reactstrap/reactstrap/issues/266)) ([c1b633a](https://github.com/reactstrap/reactstrap/commit/c1b633a))
* **Nav:** update navbar prop class value ([#265](https://github.com/reactstrap/reactstrap/pull/265))([f979aae54a8662d151d6216dac45b9dc3541ca7e] (https://github.com/reactstrap/reactstrap/pull/265/commits/f979aae54a8662d151d6216dac45b9dc3541ca7e))
* **Navbar:** rename dark prop to inverse, add toggleable size prop ([#265](https://github.com/reactstrap/reactstrap/pull/265))([3ee55f19792bd803d937837f4599ff0ee88974fb] …

chore(release): adding 4.0.0-alpha.7

---

docs/lib/Components/ProgressPage.js
docs/lib/examples/Progress.js
docs/lib/examples/ProgressAnimated.js
docs/lib/examples/ProgressLabels.js
docs/lib/examples/ProgressMax.js
docs/lib/examples/ProgressMulti.js
docs/lib/examples/ProgressStriped.js
src/Progress.js
src/__tests__/Progress.spec.js

Re worked progress a little more. Removed the cloneElement in favor of user/dev adding props `multi` and `bar`.
Progress bars can now have labels
Enhanced docs to add more various examples multiple progress bars and labels.
Added tests for the new props and labels.

feat(Progress): enhance multiple progress bars

---

CHANGELOG.md
package.json

<a name="4.0.0-alpha.8"></a>
* **cssModules:** adding missing classes ([#271](https://github.com/reactstrap/reactstrap/issues/271)) ([e8e818b](https://github.com/reactstrap/reactstrap/commit/e8e818b))
* **Progress:** enchance multiple progress bars ([#271](https://github.com/reactstrap/reactstrap/issues/274))
Progress component now requires `multi` prop on the outer component for nested progress bars. Inner Progress components will require the `bar` prop for nested progress bars.

chore(release): adding 4.0.0-alpha.8

---

src/ModalHeader.js

Recent changes to Bootstrap alpha use flexbox to position ModalHeader
title and close button, which cause the current code to incorrectly
position title and close on the opposite and wrong side.

Update ModalHeader close button

---

src/Col.js

Sometimes you don't want the `col` class by default, and setting xs={false} works but i got this error
`
Unknown prop 'xs' on <div> tag. Remove this prop from the element.
`
This prop is not removed from attributes.
https://github.com/reactstrap/reactstrap/blob/master/src/Col.js#L63

Col - fix disabled width props from being passed to div

---

src/Collapse.js
src/__tests__/Collapse.spec.js

Collapse component was rendering with `height: 0` when isOpen was set to false. This caused issues when used inside the Navbar.
Also, updates the proper navbar class, navbar-collapse.

fix Collapse component height & navbar class

---

docs/lib/Components/NavbarPage.js
src/Navbar.js
src/__tests__/Navbar.spec.js

BREAKING CHANGE:
- Navbar no longer applies a default `.navbar-toggleable` class, as it
is not required for all Navbar configurations.

fix(Navbar): remove default toggleable class

---

CHANGELOG.md
package.json

<a name="4.0.0"></a>
* **Col:** support disabled width props ([#283](https://github.com/reactstrap/reactstrap/issues/283)) ([2a36601](https://github.com/reactstrap/reactstrap/commit/2a36601))
* **Collapse:** component height & navbar class ([#284](https://github.com/reactstrap/reactstrap/issues/284)) ([0237cd4](https://github.com/reactstrap/reactstrap/commit/0237cd4))
* **Modal:** Update ModalHeader close button ([#281](https://github.com/reactstrap/reactstrap/issues/281)) ([a9dc654](https://github.com/reactstrap/reactstrap/commit/a9dc654))
* **Navbar:** remove default toggleable class ([#285](https://github.com/reactstrap/reactstrap/issues/285)) ([19b32cd](https://github.com/reactstrap/reactstrap/commit/19b32cd))
* **Collapse:** add delay prop …

chore(release): adding 4.0.0

---

CHANGELOG.md
package.json

<a name="4.0.1"></a>
* **Navbar:** updated fixed class names ([481bc14](https://github.com/reactstrap/reactstrap/commit/481bc14))
* **Navbar:** support sticky prop on navbar ([d8a9727](https://github.com/reactstrap/reactstrap/commit/d8a9727))

chore(release): adding 4.0.1

---

README.md
docs/lib/Home/index.js

Not exactly setting up an examples folder like mentioned in https://github.com/facebookincubator/create-react-app/issues/737 but this does help offer an alternative to the [react-bootstrap portion of the docs](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-bootstrap) for adding bootstrap to create-react-app.
Closes #189

docs(create-react-app): add getting started section

---

docs/lib/Components/CollapsePage.js
docs/lib/examples/CollapseEvents.js
src/Collapse.js
src/__tests__/Collapse.spec.js

Allow passing in onOpened and onClosed props as functions that are triggered after the Collapse component has finished opening or closing. Useful for performing an action that relies on the new height of the page after a Collapse component has opened or closed (such as scrolling).

feat(Collapse): Add onOpened and onClosed events (#277)

---

docs/lib/Components/AlertsPage.js
docs/lib/Components/DropdownsPage.js
docs/lib/Components/TooltipsPage.js
docs/lib/examples/AlertUncontrolledDismiss.js
docs/lib/examples/DropdownUncontrolled.js
docs/lib/examples/TooltipUncontrolled.js
src/Uncontrolled.js
src/__tests__/Uncontrolled.spec.js
src/index.js

`Alert` (dismissible), `ButtonDropdown`, `Dropdown`, `NavDropdown`, and `Tooltip` now have uncontrolled counterparts `UncontrolledAlert`, `UncontrolledButtonDropdown`, `UncontrolledDropdown`, `UncontrolledNavDropdown`, and `UncontrolledTooltip` respectfully.
These uncontrolled components can be used without the user/developer needing to control the state. They will manage their own state of when to show/hide based on the common use-case. The original components are still there for the more advanced use and non-common use-cases.
The goal of these new components is to make it easier for out-of-the-box development.
Documentation for the various components have been added to the end of each of their respective pages.

feat(Uncontrolled): add various uncontrolled components

---

CHANGELOG.md
package.json

<a name="4.1.1"></a>
* make sure everything can have a Tag ([#315](https://github.com/reactstrap/reactstrap/issues/315)) ([3373a90](https://github.com/reactstrap/reactstrap/commit/3373a90)), closes [#314](https://github.com/reactstrap/reactstrap/issues/314)
* **CardDeck:** set flex as only option ([#316](https://github.com/reactstrap/reactstrap/issues/316)) ([feb9a70](https://github.com/reactstrap/reactstrap/commit/feb9a70))

chore(release): adding 4.1.1

---

docs/lib/Components/ModalsPage.js
src/Modal.js
src/__tests__/Modal.spec.js

closes #257 
To help future proof this and prevent "cannot add class to ... on the modal", additional className props were also added.
```
wrapClassName: PropTypes.string,
modalClassName: PropTypes.string,
backdropClassName: PropTypes.string,
contentClassName: PropTypes.string,
```
I can adjust the naming or remove those if needed.

feat(Modal): add various className props to modal

---

docs/lib/examples/Layout.js

Hi all! I'm new to Reactstrap (I'm using it for a small side-project), 
but I noticed there was a small typo in one of the examples, so 
I figured I'd open a pull request to fix it rather just opening an
issue on such a small change. I read through the docs, so
hopefully everything is up to your standards, but if anything
looks out of place, I'll be sure to change it!

Fix typo in layout example

---

docs/lib/Components/ProgressPage.js
src/Progress.js
src/__tests__/Progress.spec.js

fixes #318
`className` will now be passed through to `Progress` with `bar` prop
`barClassName` allows similar pass through on single bars
`barClassName` can also be used with `bar` prop and will act as in place of `className` for convenience

fix(Progress): add custom classNames to progress-bar

---

src/Modal.js
src/__tests__/Modal.spec.js

Unmounting nested modals should remove the matching number of
`modal-open` classes from the body node. Previously, the updated class
names were computed before its children are unmounted and only updated
in the DOM afterwards. This can cause `modal-open` class name to be left
on the body if any of its children is also a modal (which is also trying
to remove those `modal-open` classes).
Here's an demo of the issue: http://www.webpackbin.com/4J7BkUsPf
1. Click on `Example 2`
2. Click on `Show Nested Model`  <- typo in the example!
3. Click on `All Done` which unmounts the example 2 component
4. Note that there is still a `modal-open` class left on the body node

fix(Modal): unmounting nested modals

---

docs/lib/Components/NavsPage.js
docs/lib/examples/NavVertical.js
src/Nav.js

Looking at the doc of Bootstrap v4 alpha.6, `Nav` needed some adjustments:
- Remove properties `inline`, `stacked` and `disabled` (they don't exist in either `nav` or `navbar`)
- Add property `vertical`
- Update doc accordingly
- Fix #295

fix(Nav): update valid properties

---

CHANGELOG.md
package.json

<a name="4.3.0"></a>
* **Modal:** default zIndex to 1050 ([#343](https://github.com/reactstrap/reactstrap/issues/343)) ([8d0f4ec](https://github.com/reactstrap/reactstrap/commit/8d0f4ec)), closes [#342](https://github.com/reactstrap/reactstrap/issues/342)
* **Nav:** update props available ([#338](https://github.com/reactstrap/reactstrap/issues/338)) ([992e4e6](https://github.com/reactstrap/reactstrap/commit/992e4e6))

chore(release): adding 4.3.0

---

.babelrc
package.json

While working on the Rollup stuff I noticed that Reactstrap uses Babel stage-0 preset but none of the options are in use.
From my experience I can recommend to not use any Babel presets that are still very much in flux like stage-0. The next release of Babel might have different stage-0 features or the stage-0 APIs introduced breaking changes.
By looking at the code I realized that the only non-standard JavaScript feature that is being used is object spread. So this PR removes stage-0 and replaces it with just object-spread.

Limit babelrc

---

docs/lib/examples/AlertDismiss.js

When I reduced the babel stages, I didn't test the docs. Looks like 1 example broke. Sorry about that.
This PR fixes it.

Fix fancy syntax in docs example

---

src/Modal.js

Modals would not work when a cssModule was passed in because the Fade component's styles wouldn't be pushed through `mapToCssModules` correctly.

pass in cssModule to Fade in Modal

---

rollup.config.js

When I removed UMD output for Rollup, I forgot to remove the UMD-only options in the rollup config.

Remove UMD-only options from rollup config

---

package.json
rollup.config.js

I incorrectly assumed that Webpack was exporting CommonJS syntax. Instead, it was exporting UMD format (which is CommonJS compatible).
So, this updates the Rollup config, also making it backwards compatible with Reactstrap 4.3.0 to address https://github.com/reactstrap/reactstrap/pull/359#issuecomment-290926692.
As extra bonus, the UMD bundles are able to be minified to 95kB! Looking at the source code, it seems like minifiers can do a better job minifying since everything is inside a function.
Changes:
- Dropped `reactstrap.cjs.js` output
- Added UMD bundle `reactstrap.min.js` (compatible with CommonJS and equivalent to output in Reactstrap 4.3)
- Added source maps back
Point all the test files at the UMD bundle:
```bash
sed -i "" "s/\.\.\/\'/\.\.\/\.\.\/dist\/reactstrap.min'/" …
```

Add UMD builds to Rollup

---

src/Button.js
src/DropdownItem.js
src/__tests__/Button.spec.js
src/__tests__/DropdownItem.spec.js

fixes: #382
`<Button>Go!</Button>` -> `<button class="btn btn-secondary">Go!</button>`
`<Button onClick={this.myHandler}>Go!</Button>` -> `<button type="button" class="btn btn-secondary">Go!</button>`
`<Button type="submit" onClick={this.myHandler}>Go!</Button>` -> `<button type="submit" class="btn btn-secondary">Go!</button>`

fix(Button): only default to button when click is handled

---

.babelrc
package.json

Rollup conversion introduced a bug where Babel wouldn't transpile import/export to CommonJS syntax in the lib dir. This PR fixes it.
Report: https://github.com/reactstrap/reactstrap/pull/359#issuecomment-290928268

Fix import/export not getting transpiled in lib dir

---

CHANGELOG.md
package.json

<a name="4.5.0"></a>
* **Button:** only default to button when click is handled ([#383](https://github.com/reactstrap/reactstrap/issues/383)) ([af3ccbe](https://github.com/reactstrap/reactstrap/commit/af3ccbe))
* **lib:** import/export not getting transpiled in lib dir ([#384](https://github.com/reactstrap/reactstrap/issues/384)) ([2e2a5da](https://github.com/reactstrap/reactstrap/commit/2e2a5da))

chore(release): adding 4.5.0

---

src/Form.js
src/FormFeedback.js
src/FormGroup.js
src/FormText.js
src/Input.js
src/Label.js
src/Media.js
src/Pagination.js
src/PaginationItem.js
src/PaginationLink.js
src/Row.js

A new linter rule lines up with new browser spec prohibits a trailing comma after the rest syntax.
Since there can be no variables defined after the rest, it is pointless to have a comma dangle there.

chore(lint): fix linter error

---

README.md
docs/lib/Home/index.js
package.json
rollup.config.js
src/Alert.js
src/Modal.js
src/__tests__/Fade.spec.js
webpack.base.config.js

Per https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html:
> react-addons-css-transition-group - Use react-transition-group/CSSTransitionGroup instead. Version 1.1.1 provides a drop-in replacement.
Please review the webpack.base.config.js changes whether it needs changes.

move to external react-transition-group dependency

---

src/Modal.js
src/__tests__/Modal.spec.js

Initially, I wanted to just report the issue, but while writing it, I found out that it was an easy fix so I did it myself.
Here is what I wanted to report:
- version: tested on`#4.5.0` but this issue can be found in the master branch
- components: `Modal`
1. add a class to the body which contains`modal-open`, e.g.: `my-modal-opened`
2. add a [Modal](https://reactstrap.github.io/components/modals/) element
3. show the modal, which will add the `modal-open` class to the body, the body class property is now `my-modal-opened modal-open`
4. hide the modal, expecting to return body class to `my-modal-opened`, but instead, the class is now `my-ed modal-open`
Demo: http://codepen.io/anon/pen/pPWVyP

fix(Modal): fix bug where closing modal removed wrong modal-open string in class

---

src/ButtonDropdown.js

The underlying Object.assign needs to have the overrides to the right it seems like
```function example(){
let props = {group: "FROM PROPERTIES" };
let propsOverwritten = Object.assign({}, props, {'group': "group from defaults"});
console.log("props first, groups overwritten", propsOverwritten);
let notOverwritten = Object.assign({}, {'group': "group from defaults"}, props);
console.log("groups first, overwritten by props as intended", notOverwritten);
}
example()
```
ES6 example https://es6console.com/j2paoelc/
Not crazy sure, but I changed the order in `reactstrap.es.js` of `g,{group:!0}` and it worked, so this seems like it would have the appropriate affect.

fix(ButtonDropdown) group={false} did nothing

---

CHANGELOG.md
package.json

<a name="4.6.0"></a>
* **ButtonDropdown:** allow overwriting the group prop ([#425](https://github.com/reactstrap/reactstrap/issues/425)) ([663551b](https://github.com/reactstrap/reactstrap/commit/663551b))
* **DropdownToggle:** add missing proptype (color) ([#402](https://github.com/reactstrap/reactstrap/issues/402)) ([c137697](https://github.com/reactstrap/reactstrap/commit/c137697))
* **Modal:** fix bug where closing modal removed wrong modal-open string in class ([#410](https://github.com/reactstrap/reactstrap/issues/410)) ([22d5c3f](https://github.com/reactstrap/reactstrap/commit/22d5c3f))
* **PropTypes:** import PropTypes from prop-types ([#395](https://github.com/reactstrap/reactstrap/issues/395)) ([9080217](https://github.com/reactstrap/reactstrap/commit/9080217))
* …

chore(release): adding 4.6.0

---

CHANGELOG.md
package.json

<a name="4.6.1"></a>
* **PropTypes:** clean up prop-types usage ([#427](https://github.com/reactstrap/reactstrap/issues/427)) ([94bbb82](https://github.com/reactstrap/reactstrap/commit/94bbb82))

chore(release): adding 4.6.1

---

package.json

fixes #430 and #432. This uses the generated lib files when requiring/importing from npm module (not not using treeshaking (webpack1)). **This does NOT fix the dist/ files (such as the UMD build) being generated incorrectly.**

chore(dist): fix release

---

package.json
rollup.config.js
src/Alert.js
src/Modal.js

Reactstrap bundle size jumped from 95kB to 335kB with the release of v4.6.0 (https://github.com/reactstrap/reactstrap/issues/472).
After observing the bundled output using [`source-map-explorer`](https://www.npmjs.com/package/source-map-explorer) I noticed that React, ReactDOM and React Transition Group all three were part of the bundle! [Visualized bundle](https://sourcemap-nrtnjyylaw.now.sh).
This was introduced when upgrading the React Transition Group package in #399. The imports were updated to point at modules that live under the `react-transition-group` package. For example:
```js
import CSSTransitionGroup from 'react-transition-group/CSSTransitionGroup';
```
By importing a module under the package, Rollup no longer found a matching entry in the list of imports that should be …

Externalize ReactTransitionGroup (fixes big file size)

---

src/DropdownToggle.js
src/__tests__/DropdownToggle.spec.js

color attribute is NOT leaked. The color attribute was added into props because it originally existed as a defaultProp (but not in the prop types) as result from a copy/paste error. The correct solution is to remove from both as it's not used in stylizing the DropdownToggle in any fashion which results in the attribute leaking as an html prop which causes HTML5 validation to error.

fix(DropdownToggle): Fixes #461 (reverting bad PR#402) which ensures

---

package.json
src/Collapse.js
src/Dropdown.js
src/DropdownItem.js
src/Fade.js
src/Popover.js
src/TabContent.js
src/Tooltip.js
src/__tests__/utils.spec.js
src/utils.js

When I was analyzing [the source map](https://sourcemap-qzasczgqli.now.sh/) for #474 I noticed that the package `lodash.omit` takes up 9.29kB!
[Looking at the source](https://unpkg.com/lodash.omit@4.5.0/index.js), we can see that it pulls in a lot of dependent lodash functions.
I've added our own omit function to `utils.js`, which minifies to 105 bytes, and works with the use cases that we provide to it:
```js
export function omit(obj, omitKeys) {
const result = {};
Object.keys(obj).forEach(key => {
if (omitKeys.indexOf(key) === -1) {
result[key] = obj[key];
}
});
return result;
}
```
This saves the user ~9kB.

Remove lodash.omit

---

docs/lib/Components/ButtonDropdownPage.js

This change fixes a typo in the button dropdown docs where "danger" was misspelled.

docs(ButtonDropdown): fix typo in Button Dropdown docs

---

src/Navbar.js
src/__tests__/Navbar.spec.js

fix(Navbar): Fixes #463 by ensuring that the default role is now empty for nav elements.

fix(Navbar): Fixes #463 by ensuring that the default role is now empty

---

src/Label.js
src/__tests__/Label.spec.js

Adds the `form-control-label` class to the `Label` component when the component is not used with a `check` or column prop. This class will be added in plain `Label` components and also `inline` `Label` components.
I might also suggest keeping an eye on https://github.com/twbs/bootstrap/issues/22173 moving forward in case further clarification on the distinction between `col-form-label` and `form-control-label` is provided
This resolves #451.

fix(Modal): Add class form-control-label to Label components

---

.babelrc
package.json
rollup.config.js

This PR will split our Rollup config in two: one for the CJS/ES build and one for UMD. This is a backwards compatible change. It will also address the minimized name issue that people experienced in Storybook.
Bundled output (names link to the actual output):
- `lib` - babelified source, stays the same
- [`dist/reactstrap.cjs.js`](https://gist.github.com/balloob/79cb8c9d930dae9ab5a0c4cf8900e823#file-reactstrap-cjs-js) - unminified CommonJS build, pointed at from `package.main`
- [`dist/reactstrap.es.js`](https://gist.github.com/balloob/79cb8c9d930dae9ab5a0c4cf8900e823#file-reactstrap-es-js) - unminified Module build, pointed at from `package.module`
- [`dist/reactstrap.min.js`](https://gist.github.com/balloob/79cb8c9d930dae9ab5a0c4cf8900e823#file-reactstrap-min-js) - minified UMD build, …

Optimize CommonJS and module build

---

README.md

Adding information for users to properly include Reactstrap library via CDN via CDNJS. Having consistent CDN location helps improve edge performance and cache hits.

docs(readme): add badges for CDN, NPM, and license + CDN info.

---

README.md

closes #495
Also, when reading the readme, it seems like the information is not 100% correct. It seems to indicate that you have to use create-react-app and that you must include bootstrap from npm. This is not the case. 
While using create-react-app is a good suggestion, especially for starting a new app, it is not required. Perhaps moving `npm install --save reactstrap react-transition-group@^1.1.2 react@^15.3.0 react-dom@^15.3.0` to the top would clarify what needs to be installed to use this app.
Bootstrap itself is not needed, at least from npm. Including a `<link>` to [their CDN](https://www.bootstrapcdn.com/alpha/) (or [bootstrap on cdnjs](https://cdnjs.com/libraries/twitter-bootstrap/)) is probably the most common way. One only needs to include bootstrap from npm if they intend to …

chore(readme): add version to install instructions

---

src/PaginationLink.js
src/__tests__/PaginationLink.spec.js

Preact defaults to empty array for children, this will check for that and null it out.
This is based on the fix for a similar issue with react-router: https://github.com/ReactTraining/react-router/pull/4423/files
Closes #494

fix(PaginationLink): handle empty children array

---

src/Alert.js
src/ModalHeader.js

Add `closeAriaLabel` so users can set the `aria-label` of the close button for ModalHeader and Alert
Closes #524

Better internationalization support for aria-labels

---

docs/lib/Components/ModalsPage.js
src/Modal.js
src/__tests__/Modal.spec.js

Add role props which defaults to dialog to the Modal component
Add labelledBy props which will output to aria-labelledby. This prop should be used by the develop to tie a title to the modal.
Closes #518

feature(Modal): add accessibility props

---

package.json

Allows all NPM scripts to be run cross-platform
Not sure if this should be merge to `master` or `v5`, or both?

Use cross-env for all npm scripts

---

src/Popover.js
src/Tooltip.js

Fixed build error: 'placements' is not exported by node_modules/popper.js/dist/esm/popper.js
Renamed `Popper` to `PopperContent` in `Tooltip.js` to match `Popover.js`.

fix(popperjs): fixed error in build

---

src/utils.js

Class names changed in `4.0.0-alpha.6`:
https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.4/js/src/modal.js#L70
https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.6/js/src/modal.js#L70

fix(Modal): Update classes for fixed content detection

---

src/PaginationLink.js
src/__tests__/PaginationLink.spec.js

The fix on #511 broke PaginationLink for any children that does not contain a `length` property.
This PR fixes it.

fix(PaginationLink): handle empty children array correctly

---

README.md
package.json
rollup.config.js
scripts/post-build
src/CarouselItem.js
src/Collapse.js
src/Fade.js
src/utils.js

* Improved inline documentation
* Updated Readme with improved CDN and distribution file information

fix(Collapse,Fade): Ensuring props don't leak to child and adding new production/limited dist builds.

---

src/utils.js

Previously it when a string target was not found in the DOM via querySelector, it would just return the `null` and bomb elswhere
Now an error is thrown to help the developer track down the issue.
Closes #620

feat(getTarget): throw when string not in DOM

---

src/utils.js

If it returns as it did does, it would be able to return null as it would immediately return and not go into the null check with throws.

fix(getTarget): do not return null; throw

---

docs/lib/Components/DropdownsPage.js

Added a list of `DropdownItem` props inside the "Properties" section of [DropdownsPage.js](https://github.com/reactstrap/reactstrap/blob/master/docs/lib/Components/DropdownsPage.js), according to #632.

docs(DropdownItem): add DropItem props section (#632)

---

README.md

Using consistent CDN (CDNJS) will ensure that all Reactstrap's dependencies remain in hot cache.
`react-popper` was originally not on CDNJS and thus the reference to unpkg; however, thanks to @TheSharpieOne it's now included.

docs(Readme): Update react-popper reference to use CDNJS for consistency with other deps

---

src/Fade.js

@TheSharpieOne ok so I know this change looks a little ridiculous, but I definitely did a decent amount of investigating and debugging on the timing of when the transition classes are applied, when rendering into subtree is occurs after adding a new div to the document.body, other ways to re-draw the transition after rendering the first time, the list goes on.
Oddly enough, this fix seems to work where adding the `fade show` class only when `status === 'entered'`, allows `Transition` to work correctly with the fade in.  I guess react-transition-group's `'exiting'` to `'entering'` event transition doesn't play well with React 16.
Let me know your thoughts / test it on your machine, it seems to work on my environment.  Sorry, I know it might seem kind of weird that it came to this one line …

 #607 animation on modal mounting

---

docs/lib/Components/CarouselPage.js
src/CarouselItem.js
src/__tests__/Carousel.spec.js

The ```img``` tag is hardcoded in CarouselItem.
This PR fixes it.

feat(CarouselItem): support tag prop on carousel item

---

docs/lib/Components/CarouselPage.js
docs/lib/examples/Carousel.js
docs/lib/examples/CarouselCustomTag.js
src/Carousel.js
src/CarouselCaption.js
src/CarouselControl.js
src/CarouselIndicators.js
src/CarouselItem.js

Addresses Issue #669 
- Adds support for carousel components to accept the className prompt
- Adds an example showing use of custom carousel tag and className

Adding className to carousel components

---

docs/lib/Components/LayoutPage.js
docs/lib/Components/index.js
docs/lib/Utilities/index.js
docs/lib/examples/Layout.js
src/Col.js
src/Label.js
src/__tests__/Col.spec.js
src/__tests__/Label.spec.js

Removed `pull`/`push` from `columnProps` and added `order` (in `Col` and `Label`). I deprecated the props but they won't work at all now; too complex to convert to `order`.
https://github.com/reactstrap/reactstrap/issues/575#issuecomment-338847760

Replace pull/push with order

---

src/CarouselIndicators.js

Fix error in the `CarouselIndicators` component that set all the items passed in the `cssModule` prop as its class name.

Fix error on `CarouselIndicators` class name when using `cssModule`

---

.eslintrc.js
docs/.eslintrc.js

The reasoning for this change is to get rid of ESLint errors shown in the IDEs
that use ESLint plugins (e.g. VSCode) because the ESLint default rules for importing
extraneus modules are not observed in docs app - it uses the modules that are not
listed in main content dependencies section.
Thanks!

Add ESLint configuration file for docs

---

README.md
docs/lib/Home/index.js
docs/lib/examples/FormGrid.js
package.json
yarn.lock

Also changes `col-form-legend` to `col-form-label` in examples

chore(docs): upgrade to bootstrap 4.0.0-beta.3

---

README.md
docs/lib/Home/index.js
package.json
yarn.lock

No breaking changes, just bug fixes and minor features. http://blog.getbootstrap.com/2018/01/18/bootstrap-4/
supersedes #760

chore(docs): upgrade to bootstrap 4.0.0 (final)

---

src/ModalHeader.js

According to the [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/modal/#modal-components), H5 is the preferred tag. Using H4 results in a misaligned close button on the modal.

Use `h5` for ModalHeader

---

src/CardTitle.js
src/__tests__/CardTitle.spec.js

Bootstrap used "h5" tag in the docs by default. According to [documentation].(https://getbootstrap.com/docs/4.0/components/card/#titles-text-and-links)
This PR fixes it.

fix(CardTitle): default tag to h5

---

src/UncontrolledNavDropdown.js

This simplifies the deprecated component to just return the preferred component (UncontrolledDropdown) with the nav prop
This removes the logic from the deprecated component.

chore(UncontrolledNavDropdown): simplify logic

---

docs/lib/Components/PopoversPage.js
docs/lib/Components/TooltipsPage.js
src/Popover.js
src/PopperContent.js
src/Tooltip.js
src/__tests__/Popover.spec.js
src/__tests__/PopperContent.spec.js
src/__tests__/Tooltip.spec.js

Added `hideArrow` prop to Popover, Tooltip and PopperContent according to #814  .

feat(Popover/Tooltip): add ability to hide arrow (#814)

---

package.json
yarn.lock

Just a simple package update. No documented breaking changes from `react-popper` and all tests still pass! For #831

chore(react-popper): upgrade to ^0.8.2 (#831)

---

docs/lib/examples/FormFeedback.js
src/FormFeedback.js
src/__tests__/FormFeedback.spec.js

Bootstrap supports form-validation success feedback messages: https://getbootstrap.com/docs/4.0/components/forms/
I added the possibility to provide a valid prop to the render method to add the `.feedback-valid` class instead of `.feedback-invalid`. It might be nicer if we would instead explicitly specify `invalid` or `valid={false}` but that would break the current behaviour. Any thoughts?

Support valid feedback messages.

---

docs/lib/Components/FormPage.js
docs/lib/examples/FormFeedback.js
src/Input.js
src/__tests__/Input.spec.js

Added invalid prop and modified valid prop to only apply class when true
Breaking Change: the valid prop no longer applies the is-invalid class when false. Use the new invalid prop to apply that class.
Closes #850

feat(Input): add invalid prop

---

docs/lib/Home/index.js

For smaller build sizes (given most people won't run a CSS minifier as part of the build) and consistency with upstream Bootstrap docs:
https://getbootstrap.com/docs/4.0/getting-started/webpack/#importing-compiled-css
Fixes #879.

docs(install): Use the minified version of Bootstrap CSS

---

docs/lib/Components/ButtonsPage.js
docs/lib/Components/CardPage.js
docs/lib/Components/NavsPage.js

Add innerRef where it was missing. innerRef is also allowed on Form but
it does not have any propTypes documented yet.

docs(*): Add innerRef.

---

docs/lib/examples/Navbar.js

This improves the documentation by aligning the "Options" DropdownMenu correctly to the right.
Previously: 
This fix:

docs(NavbarExampleSource): aligns the dropdown menu in nav bar to the right

---

package.json
src/Modal.js
src/Portal.js
src/utils.js
yarn.lock

The inclusion of `react-portal` introduced numerous issues including preventing server side rendering from working correctly. This PR fixes that and also reduces the massive increase in size resulting from that dependency. 
Fixes other issues noted in #870 which are currently not fixed in `beta.3`
Also requires React16 now. This has been talked about for awhile and signed off by @TheSharpieOne  and will not pose an issue for most libraries as the transition is seamless.
And lastly, file sizes now back to `beta.0` level
```
169K Mar 20 03:29 reactstrap.cjs.js
265K Mar 20 03:29 reactstrap.cjs.js.map
166K Mar 20 03:29 reactstrap.es.js
264K Mar 20 03:29 reactstrap.es.js.map
284K Mar 20 03:29 reactstrap.full.js
455K Mar 20 03:29 reactstrap.full.js.map
111K Mar 20 03:29 reactstrap.full.min.js …
```

Fixes Server Side Rendering, Bump Deps, Now React16 required.

---

docs/lib/examples/ButtonGroup.js

This removes `{' '}` which was added to the doc in #186, but has no effects on `Button`s inside `ButtonGroup`.
In PR[#186](https://github.com/reactstrap/reactstrap/pull/186), `{' '}` was used to make actual spaces. It did works in `Button`, but seems to have no effects in [ButtonGroup](https://reactstrap.github.io/components/button-group/). In this case, I think it's better to remove it, so that developers won't be confused by it.

chore(docs): button group spacing

---

README.md

Intent is to ensure boilerplate example is more up-to-date which is useful if people use exact external versions in keeping latest versions hot in cache.

docs(Readme): Update Readme with latest stable Reactstrap versions.

---

docs/lib/examples/Navbar.js
docs/lib/examples/NavbarToggler.js

The style guide of GitHub prefers GitHub over Github. These were the only two places with this kind of capitalisation

 docs(GitHub): fix capitalisation

---

docs/lib/examples/Navbar.js

Background colors have changed in Bootstrap. The `faded` color doesn't exist anymore so the Navbar example should use `light` instead.
See Bootstrap documentation: https://getbootstrap.com/docs/4.0/components/navbar/

Update Navbar example with actual background color

---

docs/lib/app.js

Fixes warning.
[Reacts's documentation](https://reactjs.org/docs/react-dom.html#reference) says:
> Using `ReactDOM.render()` to hydrate a server-rendered container is deprecated and will be removed in **React 17**. Use `hydrate()` instead.

fix(docs): use ReactDOM.hydrate instead of ReactDOM.render

---

docs/lib/Components/DropdownsPage.js
docs/lib/UI/PageTitle.js
src/DropdownMenu.js
src/PopperContent.js

react-popper no longer adds the attribute and it is needed for bootstrap 4.1.0
Fixes #962

fix(DropdownMenu): add x-placement attribute

---

docs/lib/examples/Dropdown.js

Example which could be bug prone. toggle() function uses actual "this.state" but sholud use "prevState".

docs(*): change toggle from using this.setState to use prevState (#954)

---

docs/lib/Components/CollapsePage.js

Should have been written as `onExited` as `onExit` is not an event.

Remove reference to `onExit` in documentation for CollapsePage

---

docs/lib/Home/index.js

Change install instruction from:
```
npm install --save reactstrap@next react react-dom
```
to:
```
npm install --save reactstrap react react-dom
```
The `next` tag points to `5.0.0-beta.3` while the latest tag points to the final `5.0.0`.
See:

Update install instructions

---

package.json

see http://2ality.com/2017/06/pkg-esnext.html#package-authors
this PR enables ship untranspiled source of reactstrap installed from github via `npm i reactstrap/reactstrap` so that you can transpile to target you want

ship untranspiled source

---

docs/lib/Components/FormPage.js
src/CustomInput.js

Fixes console warning:
Invalid argument supplied to oneOfType, expected an instance of array

Fix warning about invalid arguments to oneOfType

---

package.json

because this
```js
import "reactstrap"
```
is same as 
```js
// nothing
```
related PR https://github.com/ReactTraining/react-router/pull/6082

mark reactstrap as sideEffects free

---

docs/lib/Components/BreadcrumbsPage.js
docs/lib/Components/PaginationPage.js
docs/lib/examples/Pagination.js
docs/lib/examples/PaginationSizingLarge.js
docs/lib/examples/PaginationSizingSmall.js
docs/lib/examples/PaginationState.js
src/Breadcrumb.js
src/BreadcrumbItem.js
src/Pagination.js
src/__tests__/Breadcrumb.spec.js
src/__tests__/Pagination.spec.js

According to [Bootstrap docs](https://getbootstrap.com/docs/4.1/components/breadcrumb/#accessibility).
According to [Bootstrap docs](https://getbootstrap.com/docs/4.1/components/pagination/#overview).

chore(Breadcrumb,Pagination): improve accessibility and docs

---

src/Modal.js
src/__tests__/Modal.spec.js

Modal dialog closes when mouse button is pressed over the dialog window but released outside the window.
See angular-ui/bootstrap#5810 for video. Pull request is based on code changes made in that project.

fix(Modal): closes when dragging outside modal

---

src/Carousel.js
src/__tests__/Carousel.spec.js

fix(Carousel): allow true, false, undefined, null and children of Carousel(#1063) 
filter out booleans, null and undefined children
from render method of Carousel component
so they don't affect rendering

fix(Carousel): allow true, false, undefined, null and children of Carousel(#1063)

---

docs/lib/Components/TooltipsPage.js
src/Tooltip.js

Adding a innerRef prop to the `div` wrapping the `Tooltip` so it can accesed _from the outside_
This PR solves the issue https://github.com/reactstrap/reactstrap/issues/1089

Tooltip inner ref

---

docs/lib/Components/TooltipsPage.js
src/PopperContent.js
src/Tooltip.js

Tooltip: Custom `className` for the arrow element through `props`

---

docs/lib/Components/FormPage.js
src/CustomInput.js
src/__tests__/CustomInput.spec.js

I am not sure this API is good or not. We have 3 choices for the reference(s) for Custom Input:
1. Set `innerRef` to  `input` or `select` DOM element, like what `Input` Component do
2. Set `innerRef` to top level element of CustomInput. Like `div` for `type="file"` and `select` for `type="select"`
3. Add more props related to referencing to the component API and allow component consumers to get reference to any DOM component (wrapper div, label or input) they want.

Add innerRef to CustomInput (#1082)

---

src/CustomInput.js

Hi, for the custom input field, when I pass a react element as a label it throws a validation error from PropTypes.
With this solution I can't pass a `I agree to <a>Terms and conditions</a>` element because it's rendering as a text.
I think Custom Input should accept either text or element as labels.

Added element as a prop type for the label prop

---

CHANGELOG.md
package.json

<a name="6.3.1"></a>
* **Collapse:** add function and string to innerRef propType ([#1129](https://github.com/reactstrap/reactstrap/issues/1129)) ([f380b41](https://github.com/reactstrap/reactstrap/commit/f380b41)), closes [#1054](https://github.com/reactstrap/reactstrap/issues/1054)
* **CustomInput:** allow any node for label ([#1095](https://github.com/reactstrap/reactstrap/issues/1095)) ([c1374b4](https://github.com/reactstrap/reactstrap/commit/c1374b4))

chore(release): adding 6.3.1

---

src/Modal.js
src/__tests__/Modal.spec.js

Kept the initial click element reference being saved on `mouseDown` #1047, that prevents closing while user is selecting text and accidentally moves cursor outside modal. But changed `mouseUp` back to `click`, which doesn't fire on scrollbar press, so that user can scroll long modals again.
Fixes #1097.

fix(Modal): prevent scrollbar from closing (#1097)

---

.gitignore
CHANGELOG.md
package.json

<a name="6.4.0"></a>
* **Modal:** don't fade backdrop if there is no transition ([#1172](https://github.com/reactstrap/reactstrap/issues/1172)) ([77e7beb](https://github.com/reactstrap/reactstrap/commit/77e7beb)), closes [#1100](https://github.com/reactstrap/reactstrap/issues/1100)
* **Modal:** prevent scrollbar from closing ([#1165](https://github.com/reactstrap/reactstrap/issues/1165)) ([9d7948f](https://github.com/reactstrap/reactstrap/commit/9d7948f)), closes [#1097](https://github.com/reactstrap/reactstrap/issues/1097)
* **Dropdown:** Select first element matching pressed key ([#1160](https://github.com/reactstrap/reactstrap/issues/1160)) ([abbac56](https://github.com/reactstrap/reactstrap/commit/abbac56)), closes [#1156](https://github.com/reactstrap/reactstrap/issues/1156)
* …

chore(release): adding 6.4.0

---

src/Modal.js
src/__tests__/Modal.spec.js

For the last two bullets - I didn't add a test, but modified the existing tests.
Calls to document.body.classList removes duplicate class names.
This commit makes the Modal more resilient to these modifications by keeping a static counter on open Modals and adds "modal-open" only when the
initializing the first modal and removes "modal-open" only when destroying the last modal.
This fixes reactstrap#1189

fix(Modal): use static openCount to become resilient to classList modification

---

src/Popover.js
src/PopperContent.js
src/PopperTargetHelper.js
src/Tooltip.js
src/__tests__/Popover.spec.js
src/__tests__/Tooltip.spec.js
src/__tests__/Uncontrolled.spec.js
src/__tests__/utils.spec.js
src/utils.js

R.E. issue #1198
This pull request adds support for using React 16.3 `createRef` object as the `target` and `container` props for `Tooltip` and `Popover` components. I have updated the type definitions in [my fork](https://github.com/josh-degraw/DefinitelyTyped/tree/reactstrap-josh-degraw/types/reactstrap) so that those can be updated as well.
I added tests to cover my changes, but testing is definitely _not_ my forte, so if I did something wrong there or I'm missing something, please let me know and I'll fix / update it ASAP.

feat(Popover/Tooltip): Implented usage of react 16.3 RefObject as target

---

src/Input.js
src/__tests__/Input.spec.js

BREAKING CHANGE: previously plaintext on Input would output a 'p' tag. To better line up with bootstrap it will not output an 'input' tag. If you need a 'p' tag, provide tag="p" prop
Closes #1225

fix(Input): make plaintext output input by default

---

docs/lib/app.js
src/utils.js

fix(issue#1257) - ie foreach error on foreach

---

src/FormGroup.js

PR #1074 introduced the option to have form feedback as a tooltip. That's great!  
It also added the class `.position-relative` to `FormGroup`.  
As bootstrap states
> Be sure to have a parent with position: relative on it for tooltip positioning.
> http://getbootstrap.com/docs/4.1/components/forms/#tooltips
User should be responsible of adding that class
Resolves #1269

fix(FormGroup): remove `.position-relative`

---

src/Modal.js

Change introduced in v6.4.0 causes Modal backdrop to incorrectly render when `backdrop={false}`, if `fade={false}`.  This change will only render backdrop if `backdrop` is true.
Fixes #1267

fix(Modal): only show backdrop when prop is true

---

src/Modal.js
src/__tests__/Modal.spec.js

E.g., if a modal contains an open nested modal, don't close both when pressing the escape key.

Modal: Don't propagate handled escape keyUp event

---

docs/lib/examples/Dropdown.js
src/Dropdown.js
src/DropdownItem.js
src/__tests__/Dropdown.spec.js
src/utils.js

Closes #1287 
Adds additional event-handlers and focus management for the `Dropdown` component.
* focus is placed on the first menuitem on expand<sup>[1](https://www.w3.org/TR/wai-aria-practices-1.1/#menu)</sup>
* **only** space/enter opens the menu
* up/down arrow keyDown wraps<sup>[2](https://www.w3.org/TR/wai-aria-practices-1.1/#menu)</sup> (optional)
* home/end keys jump to first/last item<sup>[2](https://www.w3.org/TR/wai-aria-practices-1.1/#menu)</sup> 
* tab/space/esc returns focus to the menu button and closes the menu<sup>[1](https://www.w3.org/TR/wai-aria-practices-1.1/#menu)</sup>

fix(Dropdown): improve keyboard ux, WAI-ARIA

---

docs/lib/examples/CustomControls.js
src/CustomInput.js
src/__tests__/CustomInput.spec.js

In addition to the change suggested in the relevant issue, I had to make sure that `type='switch'` doesn't get passed down to the `input` element, and first gets changed to `checkbox`.
This PR addresses #1348

Add support for CustomInput type='switch'

---

src/Modal.js

By simply checking whether the click is directly on the backdrop div element (parent of the modal dialog). Works for me after a quick check (incl. nested modals).

Fix issue #1358 - don't treat clicks on Portal children as Modal backdrop clicks

---

src/TooltipPopoverWrapper.js

Via `<Popover trigger="manual" isInteractive />`.
Changed semantics for `trigger="manual"`: hide popover when clicking outside target element *and*, depending on the new `isInteractive` prop, outside the popover itself.
Would probably need some tests & documentation.

Tackle issue #1349 (backward-compatible Popover behavior)

---

src/Popover.js
src/PopperContent.js
src/Tooltip.js
src/TooltipPopoverWrapper.js
src/__tests__/TooltipPopoverWrapper.spec.js

Hi, this is my first PR. I hope I'm doing everything right! This is to address issue #363.
- default behavior for PopperContent set to fade in and out, toggleable with prop `fade={false}` in Tooltip/Popover
- default hide delay changed from 250 to 0 since now it fades out as consistent with bootstrap
- separated the popperClasses (e.g. `tooltip show`) from any extra classNames as to apply these classes to the ReactPopper child component for display purposes, and the extra classes will be applied to the root Fade component. I was not sure if this is the intended behavior, or if the extra classNames should be applied to ReactPopper instead.
- updated failing TooltipPopoverWrapper isOpen toggle test to account for the 150ms fade animation …

feat(Popper): Add fade support for ToolTip and Popover (#363)

---

src/Modal.js

Fixes bug described in https://github.com/reactstrap/reactstrap/issues/1279 where Modal.openCount becomes negative after multiple .destroy() calls, preventing "modal-open" from being added to document.body.
Solution is prevent Modal.openCount from going below a minimum of 0, rejecting decrements that result in an erroneous negative value.

Set Modal.openCount floor to 0

---

docs/lib/Components/ButtonsPage.js

I find out that the Button props documentation does not correspond to the code. Mainly it was missing `outline` prop. I have updated the documentation of props for the Button component accordingly to the code.

docs(Button): Update PropTypes and added DefaultProps

---

docs/lib/UI/Content.js
docs/static/docs.css

Currently the docs scroll with the right hand navigation. I adjusted them to have separate scrolls so the user can still select components without scrolling back up to the top of the component.

refactor(docs): added scrolling to both navigation and content

---

docs/lib/examples/CustomControls.js
src/CustomInput.js
src/__tests__/CustomInput.spec.js

I have a niche scenario where I'm using a custom input but don't want the label to be bound to the checkbox. The way I did this with regular inputs is overriding the `htmlFor`, but I couldn't do that with the custom ones. So I've added that here, along with some tests.

Added htmlFor prop for CustomInput

---

docs/lib/Components/ModalsPage.js
docs/lib/examples/ModalFocusAfterClose.js
src/Modal.js

This PR adds optional prop "returnFocusAfterClose". It allows the user to adjust if they would like to return the focus to the last focused element before the modal has opened. It is working with both "unmount" and "non unmount" close. The default value of the property is "true". Currently there is an inconsistent behaviour about focus managing after close for "unmount" and "non unmount" closing (when the Modal is destroyed the focus is returned to the last element, when it is just closed, the focus is somewhere).

feat(modal): add optional return focus after close

---

docs/lib/Components/ModalsPage.js
src/Modal.js
src/__tests__/Modal.spec.js

This PR adds a `scrollable` prop to `Modal` which applies the `modal-dialog-scrollable` class which was added in Bootstrap 4.3.0. [Here](https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content) is the relevant section of the Bootstrap documentation for reference.
Very happy to take direction on whether this needs more extensive documentation or tests to be added.
I don't believe there is an existing issue for this.

feat(Modal): add scrollable prop

---

src/TooltipPopoverWrapper.js
src/__tests__/TooltipPopoverWrapper.spec.js

For Popovers/Tooltips with trigger="click" or trigger="legacy", touches
on mobile were triggering touchstart and then click, which caused them
to open briefly and then immediately close. This removes the
touchstart event handling to fix behaviour on mobile.
#1425 

fix(TooltipPopoverWrapper) Touch not opening popover on mobile (#1425)

---

docs/lib/Components/PopoversPage.js
docs/lib/Components/TooltipsPage.js
src/TooltipPopoverWrapper.js
src/__tests__/TooltipPopoverWrapper.spec.js

Currently, Popper will by default flip a Popover or Tooltip if it's close to the edge of the container (typically the screen). For example:
```
<Tooltip placement="top" ...>
```
will get rendered as `placement="bottom"` if it's too close to the top of the screen.
This PR lets us disable this behavior if we want to by doing:
```
<Tooltip placement="top" flip={false} ...>
```

Allow popovers/tooltips to pass through flip prop

---

docs/lib/Components/DropdownsPage.js

Tiny change in docs to reflect that `maxHeight` must be a string.

Use correct typing (string, not number) for styles.maxHeight in DropdownsPage doc page

---

src/Modal.js
src/__tests__/Modal.spec.js

In server-side rendering, Modal will call init but in this time not found `document` and it's will breaks.

fix(Modal): handle init modal in SSR

---

src/FormGroup.js

fieldset allows the disabled attribute and has special handling in the browser.
This change will allow the disabled prop to be passed through when the tag is a fieldset
fixes #1546

fix(FormGroup): allow disable when tag is fieldset

---

docs/lib/Components/DropdownsPage.js
src/DropdownMenu.js
src/__tests__/DropdownMenu.spec.js

Allow the positionFixed prop to be passed through to the Popper component
Fixes #1473

fix(DropdownMenu): Allow positionFixed prop to be passed through

---

src/Dropdown.js
src/DropdownContext.js
src/DropdownToggle.js
src/__tests__/Dropdown.spec.js

- [xI have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
This fix addresses the issue where Dropdown will be passed a
`disabled` prop, yet it is still clickable. This is due to context
being passed the user-defined `toggle` prop directly, rather than
our defined `this.toggle` function that includes a check for
`disabled`.
Fixes #1542

fix: Dropdown disabled toggle issue

---

src/CustomFileInput.js
src/CustomInput.js
src/__tests__/CustomInput.spec.js
src/index.js

to display the selected files in the label.
This fixes #1460.

fix(CustomInput[type=file]): add CustomFileInput component

---

src/NavbarToggler.js
src/__tests__/NavbarToggler.spec.js

This adds the aria-label to the NavbarToggler as
seen in the bootstrap docs.
Fixes #1632

feat(NavbarToggler): add aria-label to NavbarToggler

---

docs/lib/Components/DropdownsPage.js
src/Dropdown.js

This adds a new a11y prop to Dropdrop, defaults to true.
When the a11y prop is explicitly set to false:
This changes the way tab works within the Dropdown.
tab/shift-tab will move focus to the next logic item:
tab will move down until the end. Then, at the end of the menu it will focus the next focusable item on the page and close the menu.
shift-tab will move up until the start. Then, at the beginning of the menu it will focus the toggle and close the menu.
Fixes #1441

feat(Dropdown): add a11y prop to tab moves focus

---

src/CustomInput.js
src/__tests__/CustomInput.spec.js

To confirm this change is working:
1. `npm start`
2. Open http://localhost:8080/components/form/
3. Inspect source in browser and confirm that no `type` attribute is rendered to DOM for "Custom Select" example
closes #1617

fix(CustomInput): remove type prop from input node when type is select #1617

---

docs/lib/examples/CarouselUncontrolled.js
src/UncontrolledCarousel.js
src/__tests__/UncontrolledCarousel.spec.js

See #1536
Resolves issue where if the UncontrolledCarousel contains CarouselItems with the same src, the following react error gets emitted:
```
Warning: Encountered two children with the same key, `https://xxx.png`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
closes #1536

fix(UncontrolledCarousel): use item.key instead of item.src as key prop in CarouselItems

---

src/Collapse.js
src/__tests__/Collapse.spec.js
src/__tests__/UncontrolledCollapse.spec.js

adds `aria-expanded` attribute to `<Collapse />` for accessibility
closes #1627

fix(Collapse): add aria-expanded attribute 

---

src/PopperContent.js
src/TooltipPopoverWrapper.js
src/__tests__/PopperContent.spec.js
src/__tests__/TooltipPopoverWrapper.spec.js
src/__tests__/utils.spec.js
src/utils.js

It fixes #1185 
Here is stackblitz demo with fix - https://stackblitz.com/edit/react-k8rkzv

fix(Tooltip): Support for multiple target elements

---

src/PopperContent.js
src/__tests__/PopperContent.spec.js

When a tooltip or popover does not fit in the containing element, this causes the `PopperContent` component to get into an infinite loop of switching between `placement`s in its state. This is because we attempt to update `this.state.placement` everytime popper.js flips the placement to find a better fit and pass it back as the `placement` property to `ReactPopper`.
This is a problem because the `PopperContent` component has two sources of truth for its placement. One coming from its own `placement` property, and one coming from the internal data of `ReactPopper`.
This commit fixes the issue by using `PopperContent`'s `placement` property as the initial placement of the `ReactPopper` component and allowing `ReactPopper` to manage its …

PopperContent memory leak

---

src/Dropdown.js
src/__tests__/Dropdown.spec.js

Refers to issue [#1670](https://github.com/reactstrap/reactstrap/issues/1670)

Fixed a11y property error message

---

src/__tests__/PopperContent.spec.js

I accidentally left a debug statement in https://github.com/reactstrap/reactstrap/pull/1669 that was merged. This commit removes the debug statement.

test(PopperContent): remove debug statement

---

src/Carousel.js

replace the deprecated `UNSAFE_componentWillReceiveProps` with the new `getDerivedStateFromProps` to update `state` from newly passed `props`.
Closes #1602

refactor(Carousel): replace deprecated lifecycle

---

src/Tooltip.js

New value `hover focus` is also used as the default value by bootstrap, setting the trigger value to previous value `click hover focus` causes problems on iOS (resolves issue #1676)
Resolves #1676

fix(Tooltip): default value of trigger changed

---

docs/lib/Components/ListGroupPage.js
docs/lib/examples/ListGroupHorizontal.js
src/ListGroup.js
src/__tests__/ListGroup.spec.js

This PR adds a `horizontal` prop to `ListGroup` in order to add support for [horizontal list groups](https://getbootstrap.com/docs/4.4/components/list-group/#horizontal)
Horizontal list groups can't be mixed with flush list groups, so I made the decision to ignore the `horizontal` prop if `flush` is `true`. Happy to take guidance on this point though.
The `getHorizontalClass` function I based on the [analogous function](https://github.com/reactstrap/reactstrap/blob/master/src/Nav.js#L25-L33) in the source for `Nav` in order to be consistent with existing code.

feat(ListGroup): Add horizontal prop

---

src/UncontrolledDropdown.js

Add `onToggle` to `UncontrolledDropdown`. The purpose of this new prop is to allow the user to be informed when the dropdown is toggled (opened/closed) as well as the new state of `isOpen` while still being uncontrolled.
when the dropdown is toggled, `onToggle` is called with the `event` and a `boolean` representing the new state (`true` mean the dropdown is being opened, `false` means it is being closed).

feat(UncontrolledDropdown): add onToggle callback

---

src/__tests__/utils.spec.js
src/utils.js

This commit fixes this issue described by https://github.com/reactstrap/reactstrap/issues/1686#issuecomment-546079793, where the `getTarget` function was returning `[null]` when the allElements param was true and the ref passed in had a 'current' value of `null`. The downstream effect of this was that tooltips would fail to render. The `getTarget` function now returns an empty array (`[]`).
Fixes https://github.com/reactstrap/reactstrap/issues/1686

fix(Tooltip): fix render failure if target ref is null

---

src/Modal.js
src/__tests__/Modal.spec.js

An animation was added for static backdrop modals in Bootstrap 4.4.  This can be demoed at the following url:
https://getbootstrap.com/docs/4.4/components/modal/#static-backdrop
In addition to this, I fixed the esc key from closing a modal when the backdrop is set to static as per docs:
https://getbootstrap.com/docs/4.4/components/modal/#options
`Includes a modal-backdrop element. Alternatively, specify static for a backdrop which doesn't close the modal on click or on escape key press.`

feat(Modal): Added static backdrop animation defined in Bootstrap 4.4

---

CHANGELOG.md
package.json

* remove aria-hidden attribute from tooltips and popovers ([#1747](https://github.com/reactstrap/reactstrap/issues/1747)) ([009a2bd](https://github.com/reactstrap/reactstrap/commit/009a2bd))
* **Dropdown:** Avoid preventDefault for things like F5 ([#1464](https://github.com/reactstrap/reactstrap/issues/1464)) ([305d3f0](https://github.com/reactstrap/reactstrap/commit/305d3f0)), closes [#1453](https://github.com/reactstrap/reactstrap/issues/1453)
* **DropdownContext:** wrap dropdown components to provide context prop ([64847df](https://github.com/reactstrap/reactstrap/commit/64847df)), closes [#1457](https://github.com/reactstrap/reactstrap/issues/1457) [#1462](https://github.com/reactstrap/reactstrap/issues/1462)
* **DropdownToggle:** pass innerRef to popper …

chore(release): adding 8.3.0

---

docs/lib/examples/ModalBackdrop.js
src/Modal.js
src/__tests__/Modal.spec.js

Fixes #1766 
I've also added a keyboard prop modifier to the modal example so you can play with the different keyboard/backdrop props combinations.

fix(Modal): Allow esc to close static backdrop modal when keyboard is true

---

CHANGELOG.md
package.json
scripts/release

* **Modal:** Allow esc to close static backdrop modal when keybo… ([#1767](https://github.com/reactstrap/reactstrap/issues/1767)) ([49da7b5](https://github.com/reactstrap/reactstrap/commit/49da7b5)), closes [#1766](https://github.com/reactstrap/reactstrap/issues/1766)
* **Tooltip,Popover:** account for shadowDOM target ([#1769](https://github.com/reactstrap/reactstrap/issues/1769)) ([10ccf12](https://github.com/reactstrap/reactstrap/commit/10ccf12)), closes [#1691](https://github.com/reactstrap/reactstrap/issues/1691)

chore(release): adding 8.4.1

---

src/Progress.js
src/__tests__/Progress.spec.js

Allows for more flexibility in styling
Ran into a scenario where I could use passing in styles in this manner. 
My use case involves mapping over a collection and creating slightly rounded progress bars which overlap (to cover the space created at the corners by border-radius), and I could use the ability of passing in `zIndex` values programmatically.
I realize this makes `Progress` "special", seeing as none of the other components accept the style prop. If you want me to do this for all components, let me know.
EDIT: `DropdownMenu › should not render multiple children when isOpen is false` fails, but it shouldn't be because of this PR.

feat(Progress): Allow passing in custom style object

---

docs/lib/examples/InputType.js
src/Input.js
src/__tests__/Input.spec.js

Range inputs should have the class `form-control-range` rather than `form-control`
https://getbootstrap.com/docs/4.1/components/forms/#range-inputs

feat(Input): Use form-control-range for range inputs

---

src/CustomFileInput.js
src/CustomInput.js

fix(CustomInput): hidden attribute #1741

---

docs/lib/Components/TooltipsPage.js

The default delay props for Tooltip was updated in v8 but the document is still using old value.
Actual value: https://github.com/reactstrap/reactstrap/blob/master/src/TooltipPopoverWrapper.js#L45
Related PRs:
* https://github.com/reactstrap/reactstrap/commit/87a6bda08122c0532d026d22d1b5a05837c0f2fb#diff-52e105e14e9d0085df72911cf37a3915
* https://github.com/reactstrap/reactstrap/commit/ee15c869ec955c70ef84618aec70bf2d15935bad#diff-52e105e14e9d0085df72911cf37a3915

docs(Tooltip): Update documented default value

---

docs/lib/Components/ModalsPage.js
src/Modal.js

Refers to #859.
I believe this feature is important when using Fullscreen API to request fullscreen for an element other than body. Specifying another parent for the modal allows the Modal to be used in fullscreen mode.
I couldn't add more tests because of a limitation of Enzyme to test portals.

feat(Modal): Allow passing in an element selector to append modal to

---

package.json
src/TabContent.js

New lifecycle methods were introduced in [`react@16.3`][1]
`reactstrap` has listed minimal `react` supported version as `16.3`
[1]: https://reactjs.org/blog/2018/03/29/react-v-16-3.html

refactor(TabContent): remove obsolete `react-lifecycles-compat`

---

src/PopperContent.js

This attribute is required to use Popper's `hide` modifier, in order to indicate that element left container boundaries. In such case, for example, it can be hidden. 
Closes [#1835](https://github.com/reactstrap/reactstrap/issues/1835)

feat(PopoverContent): add x-out-of-boundaries attribute

---

docs/lib/Components/ModalsPage.js
src/Modal.js

feat(Modal): match container behaviour to targetPropType like of Popover and Tooltip

---

docs/lib/UI/Banner.js
docs/lib/UI/Layout.js
docs/lib/UI/Nav.js

https://twitter.com/kwuchu/status/1267436741692133376
https://github.com/reactjs/reactjs.org
https://react-bootstrap.github.io/
Adds a banner for the Black Lives Matter movement, to spread
awareness for the cause.

in solidarity

---

CHANGELOG.md
package.json

* **Input:** Allow numbers for size prop ([#1948](https://github.com/reactstrap/reactstrap/issues/1948)) ([b4c45af](https://github.com/reactstrap/reactstrap/commit/b4c45afe658ee5008274fbf687b22d35dfe12c51))
* **Progress:** pass attributes to nested Progress bar ([#1919](https://github.com/reactstrap/reactstrap/issues/1919)) ([f3c2586](https://github.com/reactstrap/reactstrap/commit/f3c2586bbf1cc86459b5c2fd4cb025512aead432)), closes [#1847](https://github.com/reactstrap/reactstrap/issues/1847) [#1847](https://github.com/reactstrap/reactstrap/issues/1847)
* **Button:** onClick of inner button returns value of props.onClick. ([f09cdd6](https://github.com/reactstrap/reactstrap/commit/f09cdd6c2fb496948760e962383b1fa657a2c5e0))

chore(release): adding 8.6.0

---

docs/lib/Components/DropdownsPage.js
docs/lib/examples/Dropdown.js
src/DropdownItem.js
src/__tests__/DropdownItem.spec.js

Adds support for plaintext menu items.
From Bootstrap docs:
> You can also create non-interactive dropdown items with .dropdown-item-text. Feel free to style further with custom CSS or text utilities.
https://getbootstrap.com/docs/4.5/components/dropdowns/#menu-items

feat(DropdownItem): Add support for .dropdown-item-text

---

CHANGELOG.md
package.json

* **DropdownMenu:** Prevent manual styles from overriding popper styles ([#1984](https://github.com/reactstrap/reactstrap/issues/1984)) ([dc2401b](https://github.com/reactstrap/reactstrap/commit/dc2401b388777b011bc6c75426a86a78013a2b8c))
* **Progress:** Fix parent element props being spread to children ([#1970](https://github.com/reactstrap/reactstrap/issues/1970)) ([c6a790c](https://github.com/reactstrap/reactstrap/commit/c6a790c7f4bdbfac0540d53896834638edf9c793))
* **types:** Add missing innerRef typings ([#1994](https://github.com/reactstrap/reactstrap/issues/1994)) ([fe24f69](https://github.com/reactstrap/reactstrap/commit/fe24f69be2dc9953896c49be73254f7787ad34ff)), closes [#1993](https://github.com/reactstrap/reactstrap/issues/1993)
* Add typescript definitions …

chore(release): adding 8.7.0

---

types/lib/Toast.d.ts

The 8.7.0 release has a broken import of CSSModuile at https://github.com/reactstrap/reactstrap/blob/8.7.0/types/lib/Toast.d.ts#L2

Fix reference to CSSModule

---

types/index.d.ts
types/lib/Col.d.ts
types/lib/Input.d.ts
types/reactstrap-tests.tsx

- Adds missing cssModule for Col
- Fixes innerRef for Input to allow HTMLTextAreaElement
- Removes CSSModule export in root index.d.ts
Removing CSSModule in root index.d.ts prevents mistakes like #2007 from happening again.  The index.d.ts is still needed in the root folder to make dtslint run.
Also fixes #1455

fix(types): Fix Col and Input types

---

src/CarouselControl.js
src/TooltipPopoverWrapper.js
src/__tests__/PopperContent.spec.js
src/__tests__/TooltipPopoverWrapper.spec.js
src/setupTests.js

This is a tiny cleanup change to make eslint not return any errors or warnings for the project. While working on #2016, I saw there were some linting issues and had to double-check if my change caused them. It didn't! I hope by fixing these issues anyways, I'll make it easier for future contributors to pay attention to linting errors before submitting.
```
$ yarn lint
yarn run v1.22.4
$ eslint src
/Users/harry/code/reactstrap/src/__tests__/PopperContent.spec.js
151:11  warning  'wrapper' is assigned a value but never used  no-unused-vars
/Users/harry/code/reactstrap/src/__tests__/TooltipPopoverWrapper.spec.js
732:13  warning  'wrapper' is assigned a value but never used  no-unused-vars …
```

chore: Fixed all current linter warnings

---

docs/lib/Components/DropdownsPage.js
docs/lib/examples/DropdownContainer.js
src/Dropdown.js
src/DropdownMenu.js
src/__tests__/DropdownMenu.spec.js
types/lib/DropdownMenu.d.ts

- - [X] I have updated the documentation accordingly.
This is an improvement of #1513
When a Dropdown is inside a small element with overflow: hidden, it's useful to have the dropdown display directly inside of body or another container. I added the same `container` prop to DropdownMenu. Using a React Portal, this allows the dropdown to have body or any other tag as the parent.
The DropdownMenu passes its own `ref` back to the parent dropdown via an `onMenuRef` callback in the Dropdown context so that clicks outside the DropdownMenu will properly close the menu.
| Without `container` | With `container |
| --- | --- |
| ![Before container](https://user-images.githubusercontent.com/2937410/98498962-15bbbe00-21fd-11eb-94fe-05f7357ec855.gif) | ![Testing …

feat(Dropdown): Added container prop to DropdownMenu using React.portal

---

src/TooltipPopoverWrapper.js
src/__tests__/TooltipPopoverWrapper.spec.js

fix(#1990): changes priority of target element passed to popper component

---

docs/lib/Components/PopoversPage.js
docs/lib/Components/TooltipsPage.js
src/PopperContent.js
src/TooltipPopoverWrapper.js
types/lib/Popover.d.ts
types/lib/Tooltip.d.ts

react-popper has a positionFixed prop that allows the popover itself to have the `position: fixed` style, so that it doesn't flicker when applied to an element that itself is position-fixed. This change allows users of Tooltip/Popover components to specify this and pass it on to prevent flickering.
| Before | After |
| --- | --- |
| ![Before](https://user-images.githubusercontent.com/2937410/102677698-686f8a80-4158-11eb-9509-edf147ca3bfc.gif) | ![After](https://user-images.githubusercontent.com/2937410/102677705-71605c00-4158-11eb-8c9e-3f822961621a.gif) |

feat: add positionFixed prop to Tooltip and Popover

---

src/TooltipPopoverWrapper.js

Tooltips currently don't actually fade out, because as soon as `isOpen` is set to false, the render function in TooltipPopoverWrapper returns null.
This change makes it so that it returns something in the render function even when `isOpen` is false. We still only call `this.updateTarget()` when the tooltip is open. This ensures that the component still works for tooltips that open on a target appearing only after initial page rendering.
| Before | After |
| --- | --- |
| https://user-images.githubusercontent.com/2937410/102849462-0fa82800-43cc-11eb-92bb-b8f1d7a7443b.mov | https://user-images.githubusercontent.com/2937410/102849480-1767cc80-43cc-11eb-8030-40cab32414ed.mov |

fix: Make tooltips fade out

---

CHANGELOG.md
package.json

* **Modal:** Trap focus on opened modal ([#1941](https://github.com/reactstrap/reactstrap/issues/1941)) ([bf46484](https://github.com/reactstrap/reactstrap/commit/bf46484d2ee1e0d570170d59152fcd0346bfe434)), closes [#1497](https://github.com/reactstrap/reactstrap/issues/1497) [#1679](https://github.com/reactstrap/reactstrap/issues/1679)
* Make tooltips fade out ([#2041](https://github.com/reactstrap/reactstrap/issues/2041)) ([3fb5476](https://github.com/reactstrap/reactstrap/commit/3fb5476515aa01e658426e72dfbe5e7bc517b460))
* **Popover:** Select correct parent target when target children clicked ([#2038](https://github.com/reactstrap/reactstrap/issues/2038)) ([6740a57](https://github.com/reactstrap/reactstrap/commit/6740a57268dd87704c0215aa45a7e38babb5b426)), closes …

chore(release): adding 8.8.0

---

CHANGELOG.md
package.json

* Prevent popover/tooltip rendering if target not resolved ([#2059](https://github.com/reactstrap/reactstrap/issues/2059)) ([de06e9f](https://github.com/reactstrap/reactstrap/commit/de06e9ff12e954c92ba0964e615723e9a44f9269))

chore(release): adding 8.8.1

---

docs/lib/Components/ModalsPage.js
src/Modal.js
src/__tests__/Modal.spec.js
types/lib/Modal.d.ts

Fixes #2072 and fixes #2066
This PR adds a prop `trapFocus` to modal to make the trap focus behavior opt-in (original PR #1941).  This was causing issues when other modals/portals are opened while reactstrap's modal is open.

feat(Modal): Add trapFocus prop

---

src/Alert.js
src/Button.js
src/ModalHeader.js
src/ToastHeader.js
src/__tests__/Alert.spec.js
src/__tests__/Button.spec.js
src/__tests__/ModalHeader.spec.js
src/__tests__/ToastHeader.spec.js
types/lib/ToastHeader.d.ts

This PR changes `close` to `btn-close` per Bootstrap 5 changes. Bootstrap 5 no longer supports custom close icons, so this feature was removed from `ModalHeader` and `ToastHeader`.

Feat(bs5) change .close to .btn close

---

src/Row.js
src/__tests__/Row.spec.js

This PR updates `no-gutters` class to `gx-0` per Bootstrap 5 changes.

feat(bs5): change no-gutters class to gx-0

---

src/Button.js
src/__tests__/Button.spec.js

Keep prop for backwards compat
The `btn-block` class was removed in Bootstrap 5, so this PR replaces the functionality with utility classes.

feat(bs5):  Replace .btn-block with utility classes

---

src/Label.js
src/__tests__/Label.spec.js

https://getbootstrap.com/docs/5.0/migration/#forms

fix(Label): add `form-label` class for labels of vertical forms

---

src/FormGroup.js
types/lib/FormGroup.d.ts

Fixes #2415 - I also noticed that the typings didn't include the `switch` prop, so I've added it for completeness.

fix(FormGroup): dont pass switch prop to tag #2415

---

src/Offcanvas.js
types/lib/Offcanvas.d.ts

fix(Offcanvas): make types match existing direction prop

---

src/Button.js
src/CloseButton.js
src/__tests__/CloseButton.spec.js
src/index.js
stories/CloseButton.stories.js
stories/examples/CloseButton.js
stories/examples/CloseButtonDisabled.js
stories/examples/CloseButtonProps.js
stories/examples/CloseButtonWhite.js
types/lib/CloseButton.d.ts

feat(CloseButton): add close button

---

src/DropdownMenu.js

Add a boolean prop to DropdownMenu to update the Popper position every time an item is selected (see `update` documentation here: https://popper.js.org/react-popper/v2/render-props/#children).

fix: add a flag to DropdownMenu for Popper update

---

src/Collapse.js
src/__tests__/Collapse.spec.js

Updates the `react-transition-group` dependency to help with compatibility with React strict mode.
Helps towards fixing #1340 
Supersedes #1907

Fix strict mode warnings for Collapse component

---

src/Modal.js

When modals are opened, scrolling is disabled on the main page's body by setting its overflow property to 'hidden'. In certain situations when multiple modals are active, scrolling is not restored after they are closed. This fix corrects the behavior and restores the overflow status that exists on the main page's body at the time before the first modal's opening.

fix: ensure initial overflow status is stored when opening multiple modals

---

.github/workflows/release-please.yml

The release step doesn't successfully publish documentation so I updated the token to a personal access token vs the github actions `GITHUB_TOKEN`

build: publish docs should use personal access token

---

.gitignore
babel.build.config.cjs
babel.esm.config.cjs
jest.config.js
package.json
yarn.lock

- fix #2427 
- migrate from microbundle to babel

fix: treeshaking

---

src/Modal.js

For better screenreader accessibility so content outside modals is not read by screenreaders — see https://github.com/twbs/bootstrap/pull/27780 and [the attribute documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal)

feat(modal): add 'aria-modal="true"' to modal

---

src/DropdownMenu.js

As described in my comment in the issue, this simply overrides bootstrap's `display: none` style on persisted dropdowns. Popper.js does not play well with display none due to it not being able to determine positioning details for an unmounted DOM element. Simply changing the style to use `visibility` instead fixes this. The trade off is that the HTML is mounted, it just is not visible which is effectively what persist does for the dropdown menu in react.
fixes #1070

Issue 1070 Fix popper positioning when using persist in dropdown menus

---

src/UncontrolledAccordion.js
stories/examples/Accordion/AccordionExample.js
stories/examples/Accordion/AccordionFlushExample.js

**Problem:**
A component that uses an accordion component is experiencing a warning while executing the test cases in jest when toggled to a closed state. The `open` prop, defined as required, is being set to `undefined` during this process. This leads to test failures in components utilizing the Accordion due to the required prop violation.
**fix**
There is no issue in the accordion component the only concern is how we are using it, currently, the use defined in the example is violating the tests, fixing the `setOpen` to an empty string instead of undefined fix the issue. 
- [] Chore

fix: prevent setopen to set undefined value for open
