- example/js/Layout.jsx
- example/js/PopoverExample.jsx
- lib/Popover.jsx
- lib/PopoverContent.jsx
- lib/PopoverTitle.jsx
- lib/index.js
- test/Popover.spec.js
- test/PopoverContent.spec.js
- test/PopoverTitle.spec.js
Almost got this but had two snags:
The TetherContent component was calling the toggle that is passed down into it because of its `handleDocumentClick` method. The problem was that I was also calling it by assigning a click handler to the parent `_target`. This was causing the listener to fire once and the document click inside tether to fire once which effectively toggled on and then back off the popover. I circumvented this by passing in a noop function to the TetherContent toggle. This seems wrong and I assume I should feel bad. Thought I'd bring it up.
Second, I'm not doing so hot with the test spec for the Popover. Plzhalp.
@eddywashere 
Fixes #5
> Popover Component

- docs/lib/Components/LayoutPage.jsx
- docs/lib/Components/index.jsx
- docs/lib/Home/index.jsx
- docs/lib/NotFound/index.jsx
- docs/lib/UI/Footer.jsx
- docs/lib/UI/Nav.jsx
- docs/lib/examples/Layout.jsx
- docs/lib/routes.jsx
- docs/static/docs.css
- lib/Col.jsx
- lib/Container.jsx
- lib/Row.jsx
- lib/index.js
- test/Col.spec.js
- test/Container.spec.js
- test/Row.spec.js
- webpack.dev.config.js
> Layout Components

- package.json
- scripts/docs
- scripts/publish
- scripts/release
- updates release script for pushing release branches
- adds publish-release task for tagging master and publishing to npm
> build(release): update release & add publish script

- docs/lib/Components/index.jsx
adds link to additional components
> docs(components): add link to roadmap github issue

- docs/lib/Components/ButtonDropdownPage.jsx
- docs/lib/examples/ButtonDropdownMulti.jsx
- docs/lib/examples/ButtonDropdownMultiSplit.jsx
- src/Dropdown.jsx
- src/DropdownItem.jsx
- src/DropdownMenu.jsx
- src/DropdownToggle.jsx
- test/Dropdown.spec.js
- test/DropdownItem.spec.js
- test/DropdownMenu.spec.js
- test/DropdownToggle.spec.js
Added context types for isOpen and toggle for nested components under Dropdown. Also moved some components to the stateless function syntax.
> Refactor Dropdown components

- src/ButtonDropdown.jsx
- src/ButtonGroup.jsx
- src/ButtonToolbar.jsx
- src/Col.jsx
- src/Container.jsx
- src/Label.jsx
- src/Nav.jsx
- src/NavDropdown.jsx
- src/NavItem.jsx
- src/Navbar.jsx
- src/NavbarBrand.jsx
- src/NavbarToggler.jsx
- src/PopoverContent.jsx
- src/PopoverTitle.jsx
- src/Row.jsx
- test/ButtonDropdown.spec.js
- test/ButtonToolbar.spec.js
- test/NavDropdown.spec.js
Refactored some of the simpler components to use the stateless function syntax.
> refactor(Components): use stateless function syntax

- docs/lib/Components/ButtonDropdownPage.jsx
- docs/lib/Components/DropdownsPage.jsx
> docs(DropdownToggle): remove isOpen/toggle from props

- CHANGELOG.md
- package.json
Refactored the following components to use the stateless function syntax
- ButtonDropdown
- ButtonGroup
- ButtonToolbar
- Col
- Container
- DropdownMenu
- Label
- Nav
- NavDropdown
- NavItem
- Navbar
- NavBrand
- NavbarToggler
- PopoverContent
- PopoverTitle
- Row
Added Context for `isOpen` and `toggle` for components under Dropdown.
> chore(release): adding 1.3.1

- CHANGELOG.md
- package.json
Includes:
- add react addons to externals
> chore(release): adding 1.3.2

- webpack.base.config.js
References the correct external dependency
> update externals for react-addons-transition-group

- package.json
- src/Fade.jsx
- src/Modal.jsx
- test/Modal.spec.js
> Fix modal prop updates (#35)

- CHANGELOG.md
- package.json
release for:
- #35 fix(Modal): handle prop updates
> chore(release): adding 1.3.4

- CHANGELOG.md
- README.md
- docs/lib/Home/index.jsx
- package.json
Update documentation for Card in README.md and index page of docs.
**Card:** add Card related components ([#44](https://github.com/reactstrap/reactstrap/issues/44))([b782807](https://github.com/reactstrap/reactstrap/commit/b782807))
> chore(release): adding 1.4.0

- docs/lib/Home/index.jsx
- docs/static/docs.css
> fix(docs): make buttons display block on xs views

- CHANGELOG.md
- README.md
- package.json
> chore(release): adding 1.5.0

- src/ListGroup.jsx
- src/index.js
- test/ListGroup.spec.js
I wanted to help out and complete some of the missing Bootstrap components. There weren't any clear contribution guidelines, so I started with something simple like ListGroup to make sure it's acceptable. I'll add other components as I need them for my project and send PRs. Thanks for reactstrap!
> adding ListGroup component

- CHANGELOG.md
- package.json
> chore(release): adding 1.6.1

- src/Col.jsx
- test/Col.spec.js
Changes to the Col component and tests per https://github.com/reactstrap/reactstrap/issues/33#issuecomment-235954241
> Update column modifier classes to match bs4 changes

- karma.conf.js
This **should** fix the timeout issue travis ci is having.
> Fix(ci): Let karma try again on travis

- CHANGELOG.md
- package.json
<a name="2.1.0"></a>
* **breadcrumb:** Add Breadcrumb and BreadcrumbItem ([d34d738](https://github.com/reactstrap/reactstrap/commit/d34d738))
* **form:** add forms and form element components ([#67](https://github.com/reactstrap/reactstrap/issues/67)) ([7c32483](https://github.com/reactstrap/reactstrap/commit/7c32483))
> chore(release): adding 2.1.0

- docs/lib/Components/DropdownsPage.jsx
- docs/lib/examples/DropdownSizing.jsx
- src/Dropdown.jsx
- test/Dropdown.spec.js
Implements #69 
Usage
```javascript
<Dropdown size="sm">
...
</Dropdown>
<ButtonDropdown size="sm">
...
</ButtonDropdown>
```
> feat(Dropdown): add size prop

- .travis.yml
- CHANGELOG.md
- package.json
- scripts/publish
- scripts/release
<a name="2.3.0"></a>
* **inputGroup:** add InputGroup components ([#99](https://github.com/reactstrap/reactstrap/issues/99)) ([18a2ef7](https://github.com/reactstrap/reactstrap/commit/18a2ef7)), closes [#74](https://github.com/reactstrap/reactstrap/issues/74)
> Release 2.3.0

- CHANGELOG.md
- package.json
<a name="2.4.0"></a>
* **Media:** add Media component ([#94](https://github.com/reactstrap/reactstrap/issues/94)) ([d4c0f2d](https://github.com/reactstrap/reactstrap/commit/d4c0f2d))
> chore(release): adding 2.4.0

- src/Modal.jsx
- test/Modal.spec.js
This allows the modal to be open with focus on first render.
> Modal: use toggle on componentDidMount

- docs/lib/Components/PaginationPage.jsx
- docs/lib/Components/index.jsx
- docs/lib/examples/Pagination.jsx
- docs/lib/examples/PaginationSizingLarge.jsx
- docs/lib/examples/PaginationSizingSmall.jsx
- docs/lib/examples/PaginationState.jsx
- docs/lib/routes.jsx
- src/Pagination.jsx
- src/PaginationItem.jsx
- src/PaginationLink.jsx
- src/index.js
- test/Pagination.spec.js
- test/PaginationItem.spec.js
- test/PaginationLink.spec.js
- webpack.dev.config.js
References #77
* Add `Pagination`, `PaginationItem`, `PaginationLink`
* `Pagination` supports sizing
* `PaginationItem` supports active and disabled states
* `PaginationLink` supports special rendering for next and previous links
> feat(Pagination): add Pagination component

- CHANGELOG.md
- package.json
<a name="2.6.0"></a>
* **Pagination:** add Pagination component ([#108](https://github.com/reactstrap/reactstrap/issues/108)) ([fdc5c45](https://github.com/reactstrap/reactstrap/commit/fdc5c45))
> chore(release): adding 2.6.0

- docs/lib/Components/TabsPage.js
- docs/lib/Components/index.js
- docs/lib/examples/Tabs.js
- docs/lib/routes.js
- src/TabContent.js
- src/TabPane.js
- src/index.js
- test/Tabs.spec.js
- webpack.dev.config.js
PR for #72 
- Not sure if I adhered to coding style. Please let me know if I missed something
- Will squash all the commits if the changes are ok
- Have added some comments, places where I thought needed some explanation. Please feel free to remove them if you think its not right.
- If someone can point me how to update the test coverage would make sure it is 100%
> Feat: Initial implementation of Tabs component

- CHANGELOG.md
- package.json
<a name="3.1.0"></a>
* **Tabs:** add TabContent & TabPane components ([#131](https://github.com/reactstrap/reactstrap/issues/131)) ([2957ede](https://github.com/reactstrap/reactstrap/commit/2957ede))
> chore(release): adding 3.1.0

- CHANGELOG.md
- package.json
<a name="3.2.0"></a>
* **modal:** add backdrop and keyboard options ([#135](https://github.com/reactstrap/reactstrap/issues/135)) ([7bf5d0a](https://github.com/reactstrap/reactstrap/commit/7bf5d0a)), closes [#134](https://github.com/reactstrap/reactstrap/issues/134)
* **Modal:** allow for multiple modals ([#138](https://github.com/reactstrap/reactstrap/issues/138)) ([7ada8cf](https://github.com/reactstrap/reactstrap/commit/7ada8cf)), closes [#137](https://github.com/reactstrap/reactstrap/issues/137)
> chore(release): adding 3.2.0

- CHANGELOG.md
- package.json
<a name="3.2.2"></a>
* **Tooltip:** add ability to disable autohide on tooltip content hover ([#149](https://github.com/reactstrap/reactstrap/issues/149)) ([68a0ed7](https://github.com/reactstrap/reactstrap/commit/68a0ed7))
> Release 3.2.2

- docs/lib/Components/JumbotronPage.js
- docs/lib/Components/index.js
- docs/lib/Home/index.js
- docs/lib/examples/Jumbotron.js
- docs/lib/examples/JumbotronFluid.js
- docs/lib/routes.js
- docs/static/docs.css
- src/Jumbotron.js
- src/index.js
- test/Jumbotron.spec.js
- webpack.dev.config.js
Had to add a new class `jumbotron-header` in home page for docs since it was overriding the bootstrap jumbotron classes
> feat(Jumbotron): add Jumbotron Component

- README.md
Thanks for sharing the first component @TheSharpieOne! I finally got around to adding a section for this.
> docs(Readme): add related projects

- CHANGELOG.md
- README.md
- package.json
<a name="3.4.0"></a>
* **Alert:** Add Alert component ([#162](https://github.com/reactstrap/reactstrap/issues/162)) ([240e776](https://github.com/reactstrap/reactstrap/commit/240e776))
> chore(release): adding 3.4.0

- docs/lib/Components/ModalsPage.js
- docs/lib/examples/ModalNested.js
First of all, awesome work.
On the version I was using, I couldn't seem to make nested modals work - so I thought I was going to have to hack it in; seeing as it's not supported in vanilla BS.
Turns out once I put an example together it already worked! Much kudos 😄 
So, just thought I'd throw this up here in case you wanted to showcase that.
> Add nested modal example

- src/Alert.js
- src/__tests__/Alert.spec.js
```
/Users/ronny/Home/Projects/reactstrap/src/__tests__/Alert.spec.js
3:8   error  'ReactCSSTransitionGroup' is defined but never used                                                                no-unused-vars
40:35  error  The closing bracket must be aligned with the line containing the opening tag (expected column 7 on the next line)  react/jsx-closing-bracket-location
/Users/ronny/Home/Projects/reactstrap/src/Alert.js
36:5  error  'children' is missing in props validation                                                         react/prop-types
78:7  error  The closing bracket must be aligned with the line containing the opening tag (expected column 5)  react/jsx-closing-bracket-location
82:2  error  Missing semicolon …
```
> Fixed 5 ESLint errors in Alert.js and Alert.spec.js (#162)

- docs/lib/Components/TooltipsPage.js
- src/TetherContent.js
- src/Tooltip.js
- src/__tests__/TetherContent.spec.js
Fixes #174
Add `tetherRef` to TetherContent which works similarly to `ref`
> feat(tether): add ability to get tether ref

- docs/lib/Components/PopoversPage.js
- src/Popover.js
- src/__tests__/Popover.spec.js
This will pass any additional props provided to popover down to the
inner div as well as the tetherRef to the TetherContent.
> feat(popover): pass additional props down

- docs/lib/examples/Modal.js
- docs/lib/examples/ModalBackdrop.js
- docs/lib/examples/ModalNested.js
Resolves #187 by adding the space between the buttons in modals which were missed in #186 (sorry ☹️ )
> chore(docs): Fix modal button spacing

- .travis.yml
- scripts/docs
- scripts/publish
- scripts/release
enables release and publish scripts to work in travis ci
> use travis ci for releasing

- src/NavbarToggler.js
- src/__tests__/NavToggler.spec.js
remove unnecessary char in NavbarToggler component
> fix(NavbarToggler) remove unnecessary menu char

- CHANGELOG.md
- package.json
- src/Collapse.js
<a name="3.8.0"></a>
* **Collapse:** add Collapse component [#79](https://github.com/reactstrap/reactstrap/issues/79) ([#201](https://github.com/reactstrap/reactstrap/issues/201)) ([ddbf0dd](https://github.com/reactstrap/reactstrap/commit/ddbf0dd))
> chore(release): adding 3.8.0

- CHANGELOG.md
- docs/lib/Components/CollapsePage.js
- docs/lib/Components/NavbarPage.js
- docs/lib/Components/index.js
- docs/lib/examples/Collapse.js
- docs/lib/examples/NavbarToggler.js
- docs/lib/routes.js
- package.json
- src/Button.js
- src/CardLink.js
- src/Collapse.js
- src/Form.js
- src/Input.js
- src/NavLink.js
- src/__tests__/Collapse.spec.js
- src/index.js
- webpack.dev.config.js
adding a collapsible Navbar component example with NavbarToggler per #129
> add NavbarToggler example

- src/ListGroupItem.js
- src/ListGroupItemHeading.js
- src/ListGroupItemText.js
- src/__tests__/ListGroupItem.spec.js
- src/__tests__/ListGroupItemHeading.spec.js
- src/__tests__/ListGroupItemText.sepc.js
- src/index.js
I’ll write doc for #185 after the necessary components complete.
> add ListGroupItem, ListGroupItemHeading, ListGroupItemText component

- .travis.yml
- CHANGELOG.md
- package.json
<a name="3.9.0"></a>
* **DropdownToggle:** support non Button styles ([#221](https://github.com/reactstrap/reactstrap/issues/221)) ([cd3c1ce](https://github.com/reactstrap/reactstrap/commit/cd3c1ce))
* **ListGroup:** add ListGroupItem, ListGroupItemHeading, ListGroupItemText components ([#192](https://github.com/reactstrap/reactstrap/issues/192)) ([d09e81a](https://github.com/reactstrap/reactstrap/commit/d09e81a))
> chore(release): adding 3.9.0

- src/Modal.js
> fix(modal): fix multi-modal backdrop

- .travis.yml
- CHANGELOG.md
- package.json
<a name="4.0.0-alpha.1"></a>
* **Badge:** rename Tag component to Badge ([#230](https://github.com/reactstrap/reactstrap/issues/230)) ([dfc9943](https://github.com/reactstrap/reactstrap/commit/dfc9943))
> chore(release): adding 4.0.0-alpha.1

- src/Popover.js
- src/TetherContent.js
- src/Tooltip.js
- src/__tests__/Popover.spec.js
- src/__tests__/TetherContent.spec.js
- src/__tests__/Tooltip.spec.js
> Update tooltip and popover for alpha 5 changes

- src/Alert.js
- src/Collapse.js
- src/Dropdown.js
- src/Fade.js
- src/Popover.js
- src/Tooltip.js
- src/__tests__/Alert.spec.js
- src/__tests__/Collapse.spec.js
- src/__tests__/Fade.spec.js
- src/__tests__/Popover.spec.js
- src/__tests__/Tooltip.spec.js
Part of changes in alpha v6, described in #224.
> V4 alpha.6 - fix(className): update "in" to "active" for stateful components

- docs/lib/Components/ModalsPage.js
- src/Modal.js
> feature(modal): make z-index configurable

- docs/lib/Components/ProgressPage.js
- docs/lib/examples/Progress.js
- docs/static/docs.css
- package.json
- src/Progress.js
- src/__tests__/Progress.spec.js
https://github.com/twbs/bootstrap/pull/21473
> feat(Progress): update markup & support nested progress bars

- src/Alert.js
- src/Collapse.js
- src/Dropdown.js
- src/Fade.js
- src/Popover.js
- src/Tooltip.js
- src/__tests__/Alert.spec.js
- src/__tests__/Collapse.spec.js
- src/__tests__/Fade.spec.js
- src/__tests__/Popover.spec.js
- src/__tests__/Tooltip.spec.js
updating for https://github.com/twbs/bootstrap/pull/21036
> fix(className): update "active" to "show" for stateful components

- CHANGELOG.md
- docs/lib/Components/LayoutPage.js
- docs/lib/Components/index.js
- package.json
<a name="4.0.0-alpha.6"></a>
* **className:** update "active" to "show" for stateful components ([#259](https://github.com/reactstrap/reactstrap/issues/259)) ([7df9a01](https://github.com/reactstrap/reactstrap/commit/7df9a01))
* **Progress:** update markup & support nested progress bars ([#261](https://github.com/reactstrap/reactstrap/issues/261)) ([0b19b41](https://github.com/reactstrap/reactstrap/commit/0b19b41))
* **Row:** add noGutters prop ([#260](https://github.com/reactstrap/reactstrap/issues/260)) ([c79bb3e](https://github.com/reactstrap/reactstrap/commit/c79bb3e))
> Release 4.0.0 alpha.6

- webpack.base.config.js
- webpack.dev.config.js
This plugin is causing issues in docs. Going to remove it while I get other features out.
> build(webpack): remove dedupe plugin

- docs/lib/Components/NavbarPage.js
- src/Nav.js
- src/Navbar.js
- src/__tests__/Nav.spec.js
- src/__tests__/Navbar.spec.js
Nav - updates the rendered class for navbar prop.
Navbar - updates dark prop to inverse, adds toggleable prop for specifying toggleable-size class
> Nav updates

- src/Modal.js
- src/ModalBody.js
- src/ModalFooter.js
- src/ModalHeader.js
- src/Popover.js
Some files where missed the update during https://github.com/reactstrap/reactstrap/pull/206. Patch for fixing the cssModule logic for the same.
> adding missing and cleaning up cssModule

- docs/lib/Components/index.js
> fixing typo in Breadcrumbs

- src/Navbar.js
- src/__tests__/Navbar.spec.js
Navbar
- update fixed class name
- add support for sticky class
> Navbar fixed + sticky classes

- docs/lib/Components/ButtonsPage.js
- docs/lib/examples/ButtonStateful.js
> docs(Button): add example of checkbox and radio buttons

- docs/lib/Components/LayoutPage.js
- src/Col.js
- src/__tests__/Col.spec.js
> feat(Col): add custom widths ability to Col

- CHANGELOG.md
- package.json
<a name="4.1.0"></a>
* **Col:** add custom widths ability to Col ([#309](https://github.com/reactstrap/reactstrap/issues/309)) ([8487598](https://github.com/reactstrap/reactstrap/commit/8487598)), closes [#297](https://github.com/reactstrap/reactstrap/issues/297)
* **Collapse:** Add onOpened and onClosed events ([#277](https://github.com/reactstrap/reactstrap/issues/277)) ([#301](https://github.com/reactstrap/reactstrap/issues/301)) ([6c5621f](https://github.com/reactstrap/reactstrap/commit/6c5621f))
* **Uncontrolled:** add uncontrolled components ([#307](https://github.com/reactstrap/reactstrap/issues/307)) ([2f648c1](https://github.com/reactstrap/reactstrap/commit/2f648c1))
> chore(release): adding 4.1.0

- src/ButtonGroup.js
- src/ButtonToolbar.js
- src/Col.js
- src/Container.js
- src/DropdownMenu.js
- src/ModalBody.js
- src/ModalFooter.js
- src/ModalHeader.js
- src/TabContent.js
- src/TabPane.js
- src/Table.js
- src/__tests__/ButtonGroup.spec.js
- src/__tests__/ButtonToolbar.spec.js
- src/__tests__/Col.spec.js
- src/__tests__/Container.spec.js
- src/__tests__/DropdownMenu.spec.js
- src/__tests__/ModalBody.spec.js
- src/__tests__/ModalFooter.spec.js
- src/__tests__/ModalHeader.spec.js
- src/__tests__/Tabs.spec.js
fixes #314 
Everything now has `tag` prop, and some things have more (to "tag" internal/wrapping elements)
> fix(*): make sure everything can have a Tag

- src/Modal.js
> Make toggle prop optional on Modal

- CHANGELOG.md
- package.json
<a name="4.2.0"></a>
* **Modal:** unmounting nested modals ([#321](https://github.com/reactstrap/reactstrap/issues/321)) ([ecf51b2](https://github.com/reactstrap/reactstrap/commit/ecf51b2))
* **Progress:** add custom classNames to progress-bar ([#319](https://github.com/reactstrap/reactstrap/issues/319)) ([25fdb77](https://github.com/reactstrap/reactstrap/commit/25fdb77)), closes [#318](https://github.com/reactstrap/reactstrap/issues/318)
* **Modal:** add various className props to modal ([#320](https://github.com/reactstrap/reactstrap/issues/320)) ([c7b2b3e](https://github.com/reactstrap/reactstrap/commit/c7b2b3e)), closes [#257](https://github.com/reactstrap/reactstrap/issues/257)
* **Modal:** Make toggle prop optional ([#325](https://github.com/reactstrap/reactstrap/issues/325)) …
> chore(release): adding 4.2.0

- src/Modal.js
> fix(Modal): default zIndex to 1050

- src/__tests__/DropdownMenu.spec.js
> chore(test): fix DropdownMenu test

- src/Badge.js
Just a minor tweak for consistency. :)
> style(Badge): Standardising tag assignment name

- src/Col.js
- src/__tests__/Col.spec.js
> fix(Col): account for 0 col properties

- src/DropdownItem.js
- src/__tests__/DropdownItem.spec.js
> fix(DropDownItem): href makes anchor

- src/Button.js
- src/DropdownItem.js
- src/__tests__/Button.spec.js
- src/__tests__/DropdownItem.spec.js
> feat(Button): default type to button

- .travis.yml
- src/DropdownMenu.js
- src/Form.js
- src/FormFeedback.js
- src/FormGroup.js
- src/FormText.js
- src/Input.js
- src/Label.js
- src/Media.js
- src/Pagination.js
- src/PaginationItem.js
- src/PaginationLink.js
- src/__tests__/DropdownMenu.spec.js
Add custom tag property to DropdownMenu component, div by default (for bootstrap 3 only)
> feat(DropdownMenu):Add tag on dropdown-menu

- package.json
- rollup.config.js
The Rollup recommended way to handle this with the [replace plugin](https://github.com/rollup/rollup-plugin-replace).
> Replace process.env in builds (#429)

- docs/lib/Components/AlertsPage.js
- src/Alert.js
Also adds ability to add additional classes to the close button
closes #470
> fix(Alert): map close class css modules

- src/Modal.js
- src/__tests__/Modal.spec.js
> fix(Modal): add back attribute passthrough

- src/DropdownItem.js
- src/__tests__/DropdownItem.spec.js
As title, add the "active" class to the DropdownItem element.
> support the "active" property for dropdown items

- docs/lib/Home/index.js
Follow up PR for improved CDN information on main website.
> docs(Home): add improved CDN information

- src/Nav.js
- src/__tests__/Nav.spec.js
Noticed some other tests were missing, too.
> add "justified" attribute to Nav, missing unit tests for others

- src/Label.js
- src/__tests__/Label.spec.js
Changes Label's xs col class to remove the -xs part to align with bootstrap
Closes #510
> fix(Label): fix xs col class

- src/__tests__/Alert.spec.js
- src/__tests__/ModalHeader.spec.js
Added some tests for `closeAriaLabel`
> closeAriaLabel tests

- docs/lib/Components/AlertsPage.js
- docs/lib/examples/Alert.js
- docs/lib/examples/AlertContent.js
- docs/lib/examples/AlertLink.js
Update Alert documentation to stay up to date with bootstrap v4 beta.
Add light and dark colors and add examples with Link color and
Additional content.
> docs(Alert): update docs

- docs/lib/Components/BadgePage.js
- docs/lib/examples/Badge.js
- docs/lib/examples/BadgeButton.js
- docs/lib/examples/BadgePills.js
- docs/lib/examples/BadgeVariations.js
Remove default badge and update documentation so it's closer to bootstrap v4 beta
docs
> docs(Badge) update and fix docs

- docs/lib/Home/index.js
Fix https://github.com/reactstrap/reactstrap/issues/602
> remove react-addons-css-transition-group

- ISSUE_TEMPLATE.md
- docs/lib/Home/index.js
Also updates issue template to ask for more infomation.
> docs(install): specify next tag

- docs/lib/Components/NavbarPage.js
- docs/lib/UI/Nav.js
- docs/lib/examples/Navbar.js
- docs/lib/examples/NavbarToggler.js
Also updated the placement of the docs toggler itself.
> docs(NavbarToggler): add info about placement

- src/FormText.js
Allow FormText to take in React component
@TheSharpieOne
> Fix Issue #616

- rollup.config.js
- scripts/postbuild.js
In preparation for next alpha release ... including the unminified version which can be used for local development purposes.
> chore(build): Include unminified version in distribution

- src/Label.js
The `disabled` prop added a class which was not in the right place,
`disabled` should be added to the wrapping `FormGroup`.
> fix(Label): remove disabled prop

- src/ModalHeader.js
Issue: https://github.com/reactstrap/reactstrap/issues/628
> fix(ModalHeader): Use css modules in close button

- src/UncontrolledCarousel.js
> fix(UncontrolledCarousel): fix autoPlay={false}

- docs/lib/examples/ModalNested.js
Added `onClosed` prop according to #400 .
> docs(Modal): fix nested modal closing

- docs/lib/Components/NavsPage.js
- src/NavItem.js
- src/__tests__/NavItem.spec.js
Added `active` prop to NavItem according to #678  .
> feat(NavItem): Add active prop to NavItem

- CHANGELOG.md
- package.json
- rollup.config.js
<a name="5.0.0-alpha.4"></a>
* **FormGroup,Label:** Fix inline radio- and checkboxes ([#624](https://github.com/reactstrap/reactstrap/issues/624)) ([e9b7803](https://github.com/reactstrap/reactstrap/commit/e9b7803))
* **getTarget:** do not return null; throw ([#623](https://github.com/reactstrap/reactstrap/issues/623)) ([e1d3b5f](https://github.com/reactstrap/reactstrap/commit/e1d3b5f))
* **Input:** fix size prop ([#662](https://github.com/reactstrap/reactstrap/issues/662)) ([cc2bd13](https://github.com/reactstrap/reactstrap/commit/cc2bd13)), closes [#660](https://github.com/reactstrap/reactstrap/issues/660)
* **Label:** remove disabled prop ([#626](https://github.com/reactstrap/reactstrap/issues/626)) ([25c1e38](https://github.com/reactstrap/reactstrap/commit/25c1e38))
* **ModalHeader:** …
> chore(release): adding 5.0.0-alpha.4

- src/Label.js
- src/__tests__/Label.spec.js
https://github.com/reactstrap/reactstrap/issues/575#issuecomment-343564411
> Remove unused `form-control-label` class

- docs/lib/examples/CarouselCustomTag.js
> docs(Carousel): fix unique key warning and remove trailing spaces

- docs/lib/examples/FormInline.js
> chore(docs): update inline form spacing

- docs/lib/Components/PopoversPage.js
- docs/lib/Components/TooltipsPage.js
- src/Popover.js
- src/PopperContent.js
- src/Tooltip.js
- src/__tests__/Popover.spec.js
- src/__tests__/PopperContent.spec.js
- src/__tests__/Tooltip.spec.js
Implemented popper modifiers on Popover and Tooltip components, as discussed in #709. Please review :)
> feat(Popover/Tooltip): add possibility to pass modifiers to Popper.js

- docs/lib/Components/ProgressPage.js
> fix(Progress): typo in docs stripped -> striped

- src/Table.js
- src/__tests__/Table.spec.js
> feat(Table): BS4 beta 3 revert responsive table

- docs/lib/examples/InputGroupAddon.js
- docs/lib/examples/InputGroupButton.js
- docs/lib/examples/InputGroupButtonDropdown.js
- docs/lib/examples/InputGroupButtonShorthand.js
- docs/lib/examples/InputGroupOverview.js
- docs/lib/examples/InputGroupSizing.js
- src/Dropdown.js
- src/InputGroupAddon.js
- src/InputGroupButton.js
- src/InputGroupButtonDropdown.js
- src/InputGroupText.js
- src/__tests__/InputGroupAddon.spec.js
- src/__tests__/InputGroupButton.spec.js
- src/index.js
Still need to update tests but wanted to get some feedback on this first. I am leaning towards deprecating `InputGroupButton` since it's not needed for `Button`s anymore and is only useful for the shorthand. Let me know!
Fixes #759
Depends on #758
> feat(InputGroup): Update for BS 4-beta.3

- docs/lib/Components/InputGroupPage.js
- docs/lib/examples/InputGroupButtonShorthand.js
- src/InputGroupButton.js
- src/__tests__/InputGroupButton.spec.js
Change `InputGroupButton` to use `InputGroupAddon` and also deprecate
> feat(InputGroup): Deprecate InputGroupButton

- README.md
The previous example [`App.js`](https://gist.github.com/eddywashere/e13033c0e655ab7cda995f8bc77ce40d) file linked in the `README.md` contained several issues mainly caused by the use of deprecated Bootstrap 4 features.
The full list of deprecated features used in the example `App.js`:
- "inverse" property of "Navbar" has been deprecated. Please use the prop "dark"
- "toggleable" property of "Navbar" has been deprecated. Please use the prop "expand"
Furthermore, the following error Warning was produced:
- Warning: Received `true` for a non-boolean attribute `right`.
I have edited the `README.md` to link to my example [`App.js`](https://gist.github.com/Thomas-Smyth/006fd507a7295f17a8473451938f9935) file.
I have made the following changes to the `App.js` file:
- Changed the `inverse` …
> Updated example App.js Gist

- src/Input.js
- src/__tests__/Input.spec.js
> fix(Input): honor Tag prop

- src/__tests__/NavDropdown.spec.js
Added some tests for NavDropdown
> test(NavDropdown): add missing tests

- src/__tests__/InputGroupText.spec.js
Added some tests for InputGroupText
> test(InputGroupText): add missing tests

- src/UncontrolledNavDropdown.js
- src/__tests__/UncontrolledNavDropdown.spec.js
Props parameter is missing from functional component. + Added some tests for UncontrolledNavDropdown
> fix(UncontrolledNavDropdown): add missing props param

- docs/lib/Components/ButtonDropdownPage.js
- docs/lib/Components/DropdownsPage.js
- src/Dropdown.js
- src/DropdownMenu.js
- src/__tests__/Dropdown.spec.js
- src/__tests__/DropdownMenu.spec.js
Add support for dropleft and dropright (#785)
> feat(Dropdown): Add support for dropleft and dropright (#785)

- src/Modal.js
> fix(Modal): map body class name before removing

- src/__tests__/InputGroupButtonDropdown.spec.js
Added tests for `InputGroupButtonDropdown`
> test(InputGroupButtonDropdown): add missing tests

- src/__tests__/UncontrolledCarousel.spec.js
Added missing tests for `UncontrolledCarousel`
> test(UncontrolledCarousel): add missing tests

- docs/lib/examples/Layout.js
- src/Col.js
- src/__tests__/Col.spec.js
> Set col class only if no other classes are specified

- .gitignore
- docs/lib/Components/ModalsPage.js
- src/Modal.js
- src/__tests__/Modal.spec.js
Reference issue: https://github.com/reactstrap/reactstrap/issues/851
> Add centered prop to modals for modal-dialog-centered class

- src/Col.js
> Properly pass cssModule to mapToCSSModules in Col

- docs/lib/examples/InputGroupAddon.js
> fix InputGroup page

- docs/lib/Components/DropdownsPage.js
- src/Dropdown.js
- src/__tests__/Dropdown.spec.js
Added `active` prop to Dropdown according to #827   .
> feat(Dropdown): Add active prop to Dropdown

- src/Modal.js
> feat(Modal): pass event object to toggle prop

- package.json
- yarn.lock
Simple package update. No breaking changes. 
Refers to #904 #896 #872 #870
> chore(react-popper): upgrade to ^0.8.3

- src/__tests__/utils.spec.js
Added missing tests for `utils`
> test(utils): add missing tests

- src/Input.js
- src/__tests__/Input.spec.js
>  chore(Input): remove support for children content in <textarea/>

- README.md
- docs/lib/UI/DocSearch.js
- docs/lib/UI/Nav.js
- docs/lib/app.js
> feat(docs): Add search for documentation

- docs/lib/Components/ModalsPage.js
I didn't clearly see it in the docs and saw a couple closed issues with the same problem, let me know i can add a usage example if neccessary as well
> added verbage on size prop for modal

- docs/lib/examples/CarouselUncontrolled.js
- src/UncontrolledCarousel.js
> added header item prop fixes #943

- docs/lib/Home/index.js
to look same as parcel https://parceljs.org
> swap buttons on homepage

- docs/lib/Components/FormPage.js
- docs/lib/examples/CustomControls.js
- src/CustomCheckbox.js
- src/CustomCheckboxOrRadio.js
- src/CustomRadio.js
- src/__tests__/CustomCheckbox.spec.js
- src/__tests__/CustomRadio.spec.js
- src/index.js
I've marked `id` as a required prop since the CSS doesn't work without it. Perhaps it would be better to generate a default with something like `shortid` if none is given?
> Custom checkboxes/radios

- docs/lib/Home/index.js
https://github.com/reactstrap/reactstrap/pull/777/
> Updated App.js example in documentation

- README.md
Update `Adding Bootstrap` section too
> docs(Readme): Update dependency versions

- docs/lib/Components/DropdownsPage.js
- docs/lib/examples/DropdownSetActiveFromChild.js
add an example of how to use `setActiveFromChild` prop
> chore(docs): setActiveFromChild Example #977

- src/DropdownItem.js
- src/__tests__/DropdownItem.spec.js
> Fix DropdownItem onClick handler. Add supporting test.

- src/UncontrolledCollapse.js
fixed bug where uncontrolled collapse was not collapsing in mobile
> fix(UncontrolledCollapse): collapsing on mobile (#1034)

- docs/lib/Components/ListGroupPage.js
- docs/lib/examples/ListGroupFlush.js
- src/Form.js
Added an example with flush inside ListGroup
> docs(ListGroup): add example for flush to ListGroup

- src/Input.js
- src/__tests__/Input.spec.js
I change code on Input component in `src/Input.js`
And added test case for it.
> fix(Input):  type attribute should not render for select and textarea

- docs/lib/examples/ModalCustomTimeout.js
increased the transition timings for better understanding of difference between modalTransition and backdropTransition
> style(Modal): change transition time for better understanding (#1016)

- docs/lib/Components/CollapsePage.js
- src/Collapse.js
add prop innerRef to collapse component to add ref to the same
> feat(Collapse): add ref to collapse component ( #1054 )

- src/Tooltip.js
- src/__tests__/Tooltip.spec.js
> fix(Tooltip): Pass down cssModule (#1075)

- docs/lib/examples/FormFeedback.js
- src/FormFeedback.js
- src/FormGroup.js
- src/__tests__/FormFeedback.spec.js
> Form feedback tooltip

- src/Tooltip.js
I tested this on iOS and the proper behavior is observed. I hope clearing the show timeout is on the right track. (#1004 )
> #1004 fixed tooltip not disappearing on mobile

- src/Alert.js
- src/Fade.js
> feat(Alert) : add ref to Alert (#1082)

- docs/lib/Components/TooltipsPage.js
- src/Tooltip.js
- src/__tests__/Tooltip.spec.js
This PR is related to the issue #1094 
It also allows the developer to extend the capabilities of Tooltip to solve this another issue: #1072
> Toggle with event

- docs/lib/examples/Jumbotron.js
spelling incorrect of "typography"
> Typography spelling

- docs/lib/Components/TooltipsPage.js
- src/Tooltip.js
> feat(Tooltip) : add trigger for tooltip (#1022)

- README.md
and highlight the word **up to**
---
> docs(readme): update link to create-react-app guide

- docs/lib/Components/ButtonsPage.js
I noticed a grammatical error in the docs & thought I'd submit this quick edit!
> Grammatical edit for Button Docs

- docs/lib/Components/PopoversPage.js
- docs/lib/Components/TooltipsPage.js
- src/Popover.js
- src/PopperContent.js
- src/Tooltip.js
- src/UncontrolledTooltip.js
- src/__tests__/Uncontrolled.spec.js
Pass boundariesElement prop from UncrontrolledTooltip -> Tooltip -> Popper modifiers
Addresses issue #1118
> Pass boundariesElement prop from UncrontrolledTooltip -> Popper (#1118)

- src/Dropdown.js
- src/__tests__/Dropdown.spec.js
- [] My change requires a change to the documentation.
#1156
> Select first element matching pressed key in dropdown (#1156)

- docs/lib/Components/ModalsPage.js
- src/Modal.js
- src/__tests__/Modal.spec.js
- src/utils.js
- webpack.dev.config.js
- [] My change requires a change to the documentation.
I was unable to implement a test with enzyme. Focus on elements doesn't seem to advance with tabs in a mounted component. I could use some help understanding how to accomplish this test.
#310
> Trap focus in modal (#310)

- src/Modal.js
> Don't fade backdrop if there is no transition (#1100)

- src/Modal.js
Closes #1174
`document.activeElement` cannot be mocked in jsdom AFAIK, so this makes testing impossible?
> feat(Modal): return focus after modal closes

- src/Tooltip.js
Clear timers on component unmount to avoid setting state after lifecycle ends
> Clear timers on component unmount

- .eslintrc.js
- docs/lib/Components/ModalsPage.js
- docs/lib/examples/ModalCustomCloseButton.js
- src/ModalHeader.js
- [trying to] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
fixing these issues
https://github.com/reactstrap/reactstrap/issues/990
https://github.com/reactstrap/reactstrap/issues/869
> adding custom close button to examples/ modal header/ fixing typo bug

- docs/lib/Components/FormPage.js
- - [X] I have updated the documentation accordingly.
just a few small modifications
Closes #751
> docs(Form,FormFeedback,FormGroup,FormText): add props section (#751)

- src/__tests__/DropdownMenu.spec.js
Added missing test for `DropdownMenu`
> test(DropdownMenu): add missing test

- src/__tests__/InputGroupAddon.spec.js
Added missing tests for `InputGroupAddon`
> test(InputGroupAddon): add missing tests

- docs/lib/Components/CollapsePage.js
Modify Collapse page of the docs to include a brief explanation of the
Transition component props and a link to the docs from
react-transition-group/transition.
Closes #921
> docs(Collapse): Transition.propTypes (#921)

- src/Dropdown.js
- src/utils.js
> fix(Dropdown): enter key triggers onClick

- docs/lib/Components/FormPage.js
- docs/lib/Components/LayoutPage.js
- docs/lib/examples/FormGridFormRow.js
- src/Row.js
- src/__tests__/Row.spec.js
Modify <Row /> to have an additional prop `form` type `bool` which
adds class "form-row" instead of "row" when enabled.
Closes issue #1195
> feat(FormGrid): Add form-row

- docs/lib/Components/PopoversPage.js
- docs/lib/Components/TooltipsPage.js
- src/Popover.js
- src/PopperContent.js
- src/Tooltip.js
> Add DOMElement to legal options for boundariesElement proptype

- README.md
- package.json
Bumped bootstrap version to 4.1.3, for a XSS vulnerability.
https://www.cvedetails.com/cve/CVE-2018-14041/
> Yagitoshiro patch 1

- src/Badge.js
This enables you to
``` js
this.badgeRef = React.createRef()
// ...
<Badge innerRef={this.badgeRef}>A badge</Badge>
<UncontrolledTooltip target={this.badgeRef}>But no badger</UncontrolledTooltip>
```
(https://reactjs.org/docs/forwarding-refs.html)
> forward the React ref

- README.md
Update reactstrap install command
> Update reactstrap install command

- docs/lib/Components/index.js
> chore(docs): Fix alphabetic order

- src/Dropdown.js
> fix(Dropdown): Nullcheck on children (#1294)

- docs/lib/Components/TablesPage.js
- src/Table.js
> feat(Table): add innerRef prop

- src/CardSubtitle.js
- src/CardTitle.js
- src/__tests__/CardSubtitle.spec.js
- src/__tests__/CardTitle.spec.js
> fix(CardTitle,CardSubtitle): div as default tag

- docs/lib/examples/BreadcrumbNoList.js
> Fix bug in breadcrumb no list example

- src/utils.js
We need to support IE11 so I implemented PR #1262 but I was still getting errors on the `els.forEach` line when els is a NodeList (https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach)
https://github.com/reactstrap/reactstrap/pull/1262
> fix(ie foreach)

- docs/lib/Components/ModalsPage.js
> docs: Fix misspelling in documentation (Modals)

- src/Dropdown.js
- src/utils.js
> fix(Dropdown): enter key triggers onClick -- correction

- src/CardBody.js
> add innerRef to CardBody

- docs/lib/examples/InputType.js
- src/Input.js
- src/__tests__/Input.spec.js
Fixes issue #1332 that crashes the forms doc page. Changed the rendered input tag to 'p' when the `plaintext` prop is passed to the input.
- [x ] Bug fix 
- [x ] There is an open issue which this change addresses
- [ x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x ] My code follows the code style of this project.
#1332
> fix(Input): static input error

- docs/lib/Components/AlertsPage.js
> docs(typo): Fix misspelling in documentation (Alerts)

- docs/lib/Components/SpinnersPage.js
- docs/lib/Components/index.js
- docs/lib/examples/Spinner.js
- docs/lib/examples/SpinnerGrower.js
- docs/lib/routes.js
- src/Spinner.js
- src/__tests__/Spinner.spec.js
- src/index.js
> Add spinner component #1347

- src/NavLink.js
> fix(NavLink): console error while using @reach/Router #1308

- docs/lib/Components/ModalsPage.js
- docs/lib/examples/ModalDestructuring.js
- src/Modal.js
- src/__tests__/Modal.spec.js
Addresses issues:
#1061, #1115
> Feat(Modal): add destroyOnClose functionality

- src/Carousel.js
> fix(Carousel): remove inappropriate role="listbox"

- src/Modal.js
Got bug report via Sentry on production app:
- Firefox, Version: 64.0 on Ubuntu
- `TypeError: t[(n - 1)] is undefined` at `{snip} (t[i]===r){o=i;break}e.shiftKey&&0===o?(e.preventDefault(),t[n-1].focus()):e.shiftKey||o!==n-1||(e.preventDefault(),t[0].focus())}},n.handle {snip}`
I suppose there were no focusable elements found for some reason (i.e. `totalFocusable == 0`), so this exception occurred. I suggest to fix the code of Modal to avoid such exceptions in the future.
> Fixes 'TypeError: t[(n - 1)] is undefined at [...].handleTab' exception

- src/utils.js
Hi,
The function `DOMElement` in `utils.js` throws a `ReferenceError` in non-DOM environments such as Node, due to the fact that it references `Element` on the right-hand side  of an `instanceof` check, which is (most probably) undefined in non-DOM environments.
This pull request adds a small shim for the `Element` object in order to prevent `DOMElement` from throwing an error if `Element` is not defined.
> Shim Element in non-DOM environments

- src/TooltipPopoverWrapper.js
> Fix(TooltipPopoverWrapper): don't set delay if popover already open

- docs/lib/examples/Modal.js
- docs/lib/examples/ModalBackdrop.js
- docs/lib/examples/ModalCustomCloseButton.js
- docs/lib/examples/ModalCustomCloseIcon.js
- docs/lib/examples/ModalCustomTimeout.js
- docs/lib/examples/ModalDestructuring.js
- docs/lib/examples/ModalExternal.js
- docs/lib/examples/ModalFadeless.js
- docs/lib/examples/ModalNested.js
Boolean states should be set with the previous state to avoid async state change issues.
> docs(Modal): improve toggle example

- docs/lib/Components/AlertsPage.js
Add the `fade` prop to the props list for the `Alert` component docs. #1078 added this prop and an example, but neglected to add the prop to the list of props for the component docs.
> docs(Alert): add fade prop to props list

- docs/lib/examples/Collapse.js
- docs/lib/examples/CollapseEvents.js
It is recommended that you use an updater function when calling setState with reference to the previous state.
> Use callback in setState when referencing the previous state in Collapse examples

- src/Table.js
- src/__tests__/Table.spec.js
> CSS Module support for responsive Table. Fixes #1429.

- docs/lib/examples/InputGroupOverview.js
add min and max to example number input
> add min and max to example number input

- src/__tests__/Modal.spec.js
- [x ] All new and existing tests passed.
This PR adds missing tests related to "returnFocusAfterClose" prop.
> test(modal): add tests for focus management

- docs/lib/UI/Content.js
>  docs: sort components alphabetically

- docs/lib/Home/index.js
* Add a link to "Adding Bootstrap" page in reactstrap's doc site. It is because "Adding Bootstrap" section does not exist in reactstrap's README.md any more.
* Modify the link to create-react-app GitHub so as to link to create-react-app's doc site, which I think is more informative.
* Update command lines in tl;dr section based on the corresponding ones in create-react-app's doc site.
> docs(Home/index.js): link to right create-react-app instructions

- docs/lib/examples/InputGroupOverview.js
> chore(InputGroupOverview): add missing InputGroupText

- src/TooltipPopoverWrapper.js
> fix:(issue#1255-unmounted-tooltip)

- docs/lib/NotFound/index.js
> fix(NotFound): fix 404 not redirecting properly

- src/CustomFileInput.js
> Add international button text

- docs/lib/examples/Card.js
- docs/lib/examples/CardColumns.js
- docs/lib/examples/CardContentTypes.js
- docs/lib/examples/CardDecks.js
- docs/lib/examples/CardGroups.js
- docs/lib/examples/CardImageCaps.js
- docs/lib/examples/CardImageOverlay.js
- docs/static/256x186.svg
- docs/static/318x180.svg
- docs/static/318x270.svg
- [ x] Bug fix 
- [x ] There is an open issue which this change addresses
- [ x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.
fixes: 1470
> replace png images with svg on cards

- src/Dropdown.js
Hey there,
This _pull-request_ add a small piece of code to close event when Escape key is pressed (#1634)
Fixes #1634
> fix(ButtonDropdown): add close event when Escape key is pressed (#1634)

- CHANGELOG.md
Noticed a minor typo in the CHANGELOG, which made me go check that `CustomerInput` wasn't actually a thing.
> docs(changelog): Fix CustomerInput typo in CHANGELOG

- docs/lib/examples/CardGroups.js
> docs(Cards): fix broken link

- src/CarouselControl.js
This PR is for [issue# 1631](https://github.com/reactstrap/reactstrap/issues/1631)  
Added a simple style to make the cursor pointer on hover over the carousel controls
PR for [Issue# 1631](https://github.com/reactstrap/reactstrap/issues/1631)
> fix(Carousel): Add pointer on hover for controls

- package.json
- src/Col.js
- src/Label.js
- src/Progress.js
- src/__tests__/utils.spec.js
- src/utils.js
- yarn.lock
Moved lodash's functions to the project and remove dependecies.
> Remove lodash dependencies

- docs/lib/examples/ButtonDropdownUncontrolled.js
- docs/lib/examples/CustomDropdown.js
- docs/lib/examples/Dropdown.js
- docs/lib/examples/DropdownSizing.js
This PR is a fix for issue [#1659](https://github.com/reactstrap/reactstrap/issues/1659). It changes the remaining doc examples from Class components to Functional components, some of which use hooks.
> Refactored doc examples into functional components

- docs/lib/Components/PopoversPage.js
- docs/lib/Components/TooltipsPage.js
- src/Popover.js
- src/Tooltip.js
- src/__tests__/Popover.spec.js
- src/__tests__/Tooltip.spec.js
This change respects the `popperClassName` property that is exposed on the Popover and Tooltip components. `popperClassName` will be respected by appending to the div with the `popover` or `tooltip` class.
Fixes: https://github.com/reactstrap/reactstrap/issues/1484
> feat(Popover/Tooltip): add popperClassName property

- .travis.yml
> Test with NodeJS 11 and 12

- src/__tests__/TooltipPopoverWrapper.spec.js
- src/__tests__/utils.spec.js
- src/utils.js
#1686 The component expects the getTarget to return array like when allElement param is set to `true`.
> return array like when allElements parameter in getTarget is true

- docs/lib/Components/ButtonsPage.js
- docs/lib/examples/ButtonToggle.js
- src/ButtonToggle.js
- src/__tests__/ButtonToggle.spec.js
- src/index.js
resolves issue #1648
WIP right now, have to add test cases
Resolves #1648
> feat(ButtonToggle): add focus styling on button and toggle

- docs/lib/examples/Collapse.js
`isOpen={collapse}` is a contradiction, because if `collapse` is `true` then it's not collapsed and if it's `false` it is collapsed.
- [x ] Chore 
- [ x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x ] My code follows the code style of this project.
> docs(Collapse): make example more clear

- docs/lib/examples/CustomDropdown.js
Fixes #1699
Read the contributing after making my commit, commit message doesn't match form, if it's a big deal I'll come back and fix it.
> docs(Dropdown): Fix double toggle in CustomDropdown example

- docs/lib/examples/InputGroupOverview.js
> docs(InputGroupOverview): add missing InputGroupText

- docs/lib/Components/NavbarPage.js
- docs/lib/examples/Navbar.js
- src/NavbarText.js
- src/__tests__/NavbarText.spec.js
- src/index.js
> feat(Navbar): adds NavbarText component

- docs/lib/Components/LayoutPage.js
- docs/lib/examples/LayoutRowCols.js
- package.json
- src/Row.js
- src/__tests__/Row.spec.js
This is the new row columns feature from Bootstrap 4.4:
https://getbootstrap.com/docs/4.4/layout/grid/#row-columns
> feat(Row): Add row columns support

- README.md
> Added formstrap to the wild lists

- docs/lib/Components/CarouselPage.js
Just a small doc change.  It's my first time committing, so I did my best, but may have missed something.
> docs: Adding interval autoplay disable notes

- docs/lib/Components/LayoutPage.js
- docs/lib/examples/ContainerResponsive.js
- docs/static/docs.css
- src/Container.js
- src/__tests__/Container.spec.js
> feat(Container): Added responsive container support

- docs/lib/Components/CarouselPage.js
- src/Carousel.js
> feat(Carousel): Add touch swipe support

- docs/lib/examples/FormGrid.js
> docs: fix form example showing multiselect

- src/TooltipPopoverWrapper.js
> fix(Tooltip): autohide broken since default delay was zero (#1692)

- docs/lib/Components/DropdownsPage.js
Currently, the dropdown for the right alignment example shows as somewhat centered due to the dropdown menu content.  I changed it so that the dropdown is now centered in the page, so it will properly show the dropdown menu as right aligned.  I've also updated the code example to reflect what is being rendered.
> docs(Dropdown): Update alignment example to better illustrate right alignment

- src/TooltipPopoverWrapper.js
> fix(Tooltip): fix nested elements within target

- src/TooltipPopoverWrapper.js
> fix: remove aria-hidden attribute from tooltips and popovers

- src/Modal.js
- src/__tests__/Modal.spec.js
> fix(Modal): Prevent static backdrop animation when modal clicked

- CHANGELOG.md
- package.json
- scripts/release
* **Modal:** Prevent static backdrop animation when modal clicked ([#1755](https://github.com/reactstrap/reactstrap/issues/1755)) ([79efb4a](https://github.com/reactstrap/reactstrap/commit/79efb4a))
> chore(release): adding 8.3.2

- src/Dropdown.js
- src/DropdownItem.js
- src/DropdownMenu.js
- src/DropdownToggle.js
- src/__tests__/DropdownItem.spec.js
- src/__tests__/DropdownMenu.spec.js
- src/__tests__/DropdownToggle.spec.js
…text prop"
This reverts commit 64847df4a858c4ad7fc4c0f876fcff9a456ee55b.
64847df contained a breaking change, per semvar it needs to be removed and another version published on the same major ver which does not contain the breaking change.
Fixes #1758
> fix: revert breaking change

- src/Collapse.js
- src/__tests__/Collapse.spec.js
- src/__tests__/UncontrolledCollapse.spec.js
Reverts reactstrap/reactstrap#1657
Fixes #1757
> Revert "fix(Collapse): add aria-expanded attribute "

- CHANGELOG.md
- package.json
* revert breaking change ([#1760](https://github.com/reactstrap/reactstrap/issues/1760)) ([eb37426](https://github.com/reactstrap/reactstrap/commit/eb37426))
> chore(release): adding 8.4.0

- README.md
https://github.com/0wczar/airframe-react - http://dashboards.webkom.co/react/airframe/ - Airframe provides all the components a developer needs to build data-intensive web apps using React.
> Suggestion to add a link to the "On the wild”

- docs/lib/Components/DropdownsPage.js
> docs: change maxHeight from int to string in Dropdowndocs

- src/TooltipPopoverWrapper.js
> fix(Tooltip,Popover): account for shadowDOM target

- src/Label.js
- src/__tests__/Carousel.spec.js
- src/__tests__/CustomInput.spec.js
- src/__tests__/DropdownMenu.spec.js
- src/__tests__/Input.spec.js
- src/__tests__/InputGroupButtonDropdown.spec.js
Fixed the failing unit test in DropdownMenu.  Also cleaned up the various warnings from other tests.
> test: Fix failing unit test and warnings

- docs/lib/PremiumThemes/index.js
> Docs(PremiumThemes): add Creative Tim themes

- docs/lib/examples/Tabs.js
> Fix: Typo in Tabs Example

- README.md
> Fix link to create-react-app Getting Started documentation

- docs/lib/PremiumThemes/premium.js
> Added wrappixel products for premium themes

- README.md
**Change**
`npm install` by default installs packages as dependencies (in npm>=5)
https://stackoverflow.com/a/19578808
> docs: npm --save no longer needed

- docs/lib/Components/ProgressPage.js
- src/Progress.js
- - [X] I have updated the documentation accordingly.
This PR passes `aria-valuetext` and `aria-labelledby` to Progress component. 
It also set default min value, allowing users to set custom `min` prop.
#1681
> feat(Progress): add aria props (#1681)

- src/CustomFileInput.js
- src/CustomInput.js
- src/Input.js
> fix(Input): Aria-invalid attribute

- src/DropdownToggle.js
Replaced OR operator with null-coalescing operator to allow 0 value but not nullish values
#1496
> fix(DropdownToggle): fix 0 value #1496

- CHANGELOG.md
- package.json
* **Carousel:** ie11 compatibility changes([#799](https://github.com/reactstrap/reactstrap/issues/799)) ([#1585](https://github.com/reactstrap/reactstrap/issues/1585)) ([1fd2d22](https://github.com/reactstrap/reactstrap/commit/1fd2d22)), closes [/github.com/reactjs/react-transition-group/blob/9e3b2d3c09b78e755bdc837b7b38337812ede2c9/src/TransitionGroup.js#L11](https://github.com//github.com/reactjs/react-transition-group/blob/9e3b2d3c09b78e755bdc837b7b38337812ede2c9/src/TransitionGroup.js/issues/L11)
* **CustomInput:** hidden attribute [#1741](https://github.com/reactstrap/reactstrap/issues/1741) ([#1777](https://github.com/reactstrap/reactstrap/issues/1777)) ([bb39b55](https://github.com/reactstrap/reactstrap/commit/bb39b55))
* **DropdownToggle:** fix 0 value …
> chore(release): adding 8.5.0

- src/polyfill.js
> Fix missing `window` causing NextJS builds to fail

- src/Button.js
- src/__tests__/Button.spec.js
> feat(Button): onClick of inner button returns value of props.onClick.

- webpack.docs.config.js
> docs: add spinners page to paths for pre-render

- src/Progress.js
- src/__tests__/Progress.spec.js
> FIX #1847: Passes attributes to nested Progress bar

- src/Input.js
> fix(Input): Allow numbers for size prop

- src/Progress.js
Fixes #1969
This also adds to ability to customize the progress bar element via tag
> fix(Progress): Fix parent element props being spread to children

- docs/lib/Components/ButtonDropdownPage.js
See https://github.com/reactstrap/reactstrap/blob/b4c45afe658ee5008274fbf687b22d35dfe12c51/docs/lib/examples/ButtonDropdownMultiSplit.js#L12
> docs: Fix code example for split button dropdowns

- docs/lib/Components/CollapsePage.js
Adds a sentence to describe the defaultOpen prop.
> Document the defaultOpen prop

- types/lib/Fade.d.ts
- types/lib/Modal.d.ts
- types/lib/Table.d.ts
> fix(types): Add missing innerRef typings

- docs/lib/Home/index.js
- docs/lib/UI/Banner.js
- docs/static/docs.css
- Fix BLM banner covering hamburger button on small mobile screens
- Fix "Components" button sizing on mobile
- Remove unneeded scrollbar on main page
> docs: Fix layout issues

- package.json
> chore: Allow React 17 in peer deps

- PULL_REQUEST_TEMPLATE.md
Fix the typos in the pull request template
> chore(PR): fix typos in the pull request template

- docs/lib/examples/Card.js
- docs/lib/examples/CardAlignment.js
- docs/lib/examples/CardBackgrounds.js
- docs/lib/examples/CardColumns.js
- docs/lib/examples/CardContentTypes.js
- docs/lib/examples/CardDecks.js
- docs/lib/examples/CardGroups.js
- docs/lib/examples/CardHeaderFooter.js
- docs/lib/examples/CardImageCaps.js
- docs/lib/examples/CardImageOverlay.js
- docs/lib/examples/CardOutline.js
- docs/lib/examples/CardSizing.js
Update card title and subtitle in the examples to be in sync with the upstream bootstrap docs
Closes #1991
> docs(card): Update Card examples

- CHANGELOG.md
- package.json
* **types:** Fix Col and Input types ([#2008](https://github.com/reactstrap/reactstrap/issues/2008)) ([363dfbe](https://github.com/reactstrap/reactstrap/commit/363dfbe6a46ef04c61f0b249bd5c0a80ec1c1e3e))
* **types:** Fix reference to CSSModule ([#2007](https://github.com/reactstrap/reactstrap/issues/2007)) ([54afca4](https://github.com/reactstrap/reactstrap/commit/54afca47879fbb8a2713b57ff452fa566e5255d1))
> chore(release): adding 8.7.1

- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
I realized I forgot to change the typings for my change #2016. To make sure other contributors don't miss this, I added a note to both the PR template and the CONTRIBUTING.md file
> chore: Updated pull request template to mention Typescript, eslint

- ISSUE_TEMPLATE.md
- README.md
Adds CodeSandbox references in the readme and issue template
Closes #2030
> chore: Add CodeSandbox references

- README.md
- docs/lib/Components/PopoversPage.js
- docs/lib/Components/TooltipsPage.js
- docs/lib/Home/index.js
> docs: Update react-popper link

- src/TooltipPopoverWrapper.js
> fix: Prevent popover/tooltip rendering if target not resolved

- docs/lib/Components/DropdownsPage.js
- docs/lib/examples/Dropdown.js
docs: Improve dropdown page
+ Add [missing className prop of Dropdown component](https://github.com/reactstrap/reactstrap/blob/bd313c23e5d1dee984e65e5fdc167fe83f3831a9/src/Dropdown.js#L24) to docs
+ Fix indent issue in an example
> docs: Improve dropdown page

- docs/lib/Components/ProgressPage.js
- src/Progress.js
- src/__tests__/Progress.spec.js
- types/lib/Progress.d.ts
#1771 accidentally broke setting styles in the parent progress container.  This fixes that by pulling the feature into a new prop called `barStyle`.
Fixes #2071
> feat(Progress): Add barStyle prop

- CHANGELOG.md
- package.json
* **Modal:** Add trapFocus prop ([#2073](https://github.com/reactstrap/reactstrap/issues/2073)) ([6e0fd56](https://github.com/reactstrap/reactstrap/commit/6e0fd565b66c9a16b3187adcb71d52d2d9db2902))
* **Progress:** Add barStyle prop ([#2075](https://github.com/reactstrap/reactstrap/issues/2075)) ([27faa8e](https://github.com/reactstrap/reactstrap/commit/27faa8e5c575314070f1a35e1969c81e25b13942))
> chore(release): adding 8.9.0

- package.json
- yarn.lock
This PR will update bootstrap to `5.0.0-beta2` in the `bootstrap5` branch. This will allow us to split up https://github.com/reactstrap/reactstrap/pull/2102 into multiple PRs, as requested.
Related to, but does not resolve: #1748
> chore(deps): Upgrade bootstrap to 5.0.0-beta2

- src/Badge.js
- src/__tests__/Badge.spec.js
This PR updates the badge classes which were changed in Bootstrap 5.
`badge-*` -> `bg-*`
`badge-pill` -> `rounded-pill`
> feat(bs5): update badge classes

- docs/lib/PremiumThemes/premium.js
I have added a new premium theme based on **reactstrap**, "Vuexy Admin Template" by "Pixinvent" as per our email communication.
> chore(docs): New premium theme Vuexy Admin Template By Pixinvent

- README.md
- docs/lib/Home/index.js
- src/CarouselControl.js
- src/DropdownToggle.js
- src/Label.js
- src/PaginationLink.js
- src/Spinner.js
- src/__tests__/DropdownToggle.spec.js
- src/__tests__/Label.spec.js
- src/__tests__/PaginationLink.spec.js
- src/__tests__/Spinner.spec.js
This PR converts `sr-only` to `visually-hidden` per changes to Bootstrap 5.
> feat(bs5): convert .sr-only to .visually-hidden

- docs/lib/NotFound/index.js
- docs/lib/UI/Banner.js
- docs/lib/UI/Nav.js
- docs/lib/examples/DropdownSetActiveFromChild.js
- docs/lib/examples/FormInline.js
- docs/lib/examples/Navbar.js
- docs/lib/examples/NavbarToggler.js
- docs/lib/examples/PopoverMulti.js
- docs/lib/examples/TooltipMulti.js
- src/ToastHeader.js
- types/reactstrap-tests.tsx
Bootstrap 5 renamed margin utility classes. This PR updates those classes to the new convention.
`ml-*` & `mr-*` are now `ms-*` & `me-*`
> feat(bs5):  Rename margin utils

- docs/lib/Components/FormPage.js
- src/FormGroup.js
- src/__tests__/FormGroup.spec.js
This PR replaces `form-group` with `mb-3` per Bootstrap 5 changes.
> feat(bs5): replace form-group class with mb-3

- docs/lib/Components/ModalsPage.js
- docs/lib/examples/ModalFullscreen.js
- src/Modal.js
- src/__tests__/Modal.spec.js
- types/lib/Modal.d.ts
This PR adds support for the new fullscreen modals introduced in Bootstrap 5.
> feat(modal): add fullscreen option to Modal component

- docs/lib/Components/LayoutPage.js
- docs/lib/examples/ContainerResponsive.js
- src/Col.js
- src/Label.js
- src/Row.js
- types/lib/Col.d.ts
- types/lib/Label.d.ts
- types/lib/Row.d.ts
- types/reactstrap-tests.tsx
This PR adds support for the new XXL breakpoints in Bootstrap 5.
> feat(bs5): Support xxl breakpoint

- docs/lib/Components/CarouselPage.js
- docs/lib/Components/DropdownsPage.js
- src/Carousel.js
- src/DropdownMenu.js
- src/__tests__/Carousel.spec.js
- src/__tests__/DropdownMenu.spec.js
- types/lib/Carousel.d.ts
- types/lib/DropdownMenu.d.ts
This PR adds the new dark option to `DropdownMenu` and `Carousel`.
> Feat(bs5) dark props

- docs/lib/Components/DropdownsPage.js
- docs/lib/Components/PopoversPage.js
- docs/lib/Components/TooltipsPage.js
- docs/lib/examples/PopoverUpdate.js
- docs/lib/examples/TooltipUpdate.js
- package.json
- src/DropdownMenu.js
- src/Popover.js
- src/PopperContent.js
- src/Tooltip.js
- src/TooltipPopoverWrapper.js
- src/__tests__/DropdownMenu.spec.js
- src/__tests__/PopperContent.spec.js
- src/__tests__/TooltipPopoverWrapper.spec.js
- types/lib/DropdownMenu.d.ts
- types/lib/Popover.d.ts
- types/lib/Tooltip.d.ts
- types/reactstrap-tests.tsx
- yarn.lock
Bootstrap 5 has updated to popper 2. This PR updates reactstrap to use popper 2 for consistency and updates to the new arrow classes in Bootstrap 5.
Breaking changes:
- `modifiers` prop will now conform to the new popper2 [modifiers](https://popper.js.org/docs/v2/modifiers/), which take an array instead of an object.
- `offset` prop is now an array of 2 numbers that represent skidding and distance. See [docs](https://popper.js.org/docs/v2/modifiers/offset/#offset-1) for more details.
Resolves: https://github.com/reactstrap/reactstrap/issues/1972
> Feat(bs5) update tooltip/popover classes and migrate to Popper 2

- docs/lib/Components/ButtonDropdownPage.js
- docs/lib/Components/DropdownsPage.js
- src/Dropdown.js
- src/DropdownContext.js
- src/DropdownMenu.js
- src/__tests__/Dropdown.spec.js
- src/__tests__/DropdownMenu.spec.js
- types/lib/Dropdown.d.ts
Converts dropdown & dropdown menu to use Bootstrap 5's new direction classes `start` and `end`. These changes are backwards compatible with the old `left` and `right` properties.
> Convert dropdown & dropdown menu to rtl

- .travis.yml
Update travis to handle prerelease deploys
> chore(travis): Update to handle prerelease deploys

- src/Carousel.js
- src/CarouselIndicators.js
- src/CarouselItem.js
- src/__tests__/Carousel.spec.js
- types/lib/Carousel.d.ts
This updates Carousel to Bootstrap v5.0.0
- Use renamed RTL class names
- Updates indicator markup and selectors for correct styling
- Add support for `carousel-fade`
> V5 Carousel Updates

- docs/lib/PremiumThemes/premium.js
> Adding MDBReact To Themes Premium List

- docs/lib/Components/AccordionPage.js
- docs/lib/examples/Accordion.js
- docs/lib/examples/AccordionFlush.js
- docs/lib/examples/UncontrolledAccordion.js
- docs/lib/examples/UncontrolledAccordionStayOpen.js
- src/Accordion.js
- src/AccordionBody.js
- src/AccordionHeader.js
- src/UncontrolledAccordion.js
- src/__tests__/Accordion.spec.js
- src/__tests__/AccordionBody.spec.js
- src/__tests__/AccordionHeader.spec.js
- types/lib/Accordion.d.ts
- types/lib/UncontrolledAccordion.d.ts
- types/lib/index.d.ts
Update Accordion to Bootstrap 5.0.0
- Add flush Accordion
- Rename openId to open and optionally allow array of ids to allow multiple open AccordionItems
- Add `stayOpen` to UncontrolledAccordion prop to allow multiple open AccordionItems
> V5 update accordion

- docs/lib/Components/PlaceholderPage.js
- docs/lib/Components/index.js
- docs/lib/examples/Placeholder.js
- docs/lib/examples/PlaceholderAnimation.js
- docs/lib/examples/PlaceholderColor.js
- docs/lib/examples/PlaceholderSizing.js
- docs/lib/examples/PlaceholderWidth.js
- docs/lib/routes.js
- package.json
- src/Col.js
- src/Placeholder.js
- src/PlaceholderButton.js
- src/__tests__/Placeholder.spec.js
- src/__tests__/PlaceholderButton.spec.js
- src/index.js
- types/lib/Placeholder.d.ts
- types/lib/PlaceholderButton.d.ts
- yarn.lock
> Feat placeholder #1748

- docs/lib/Components/CollapsePage.js
- docs/lib/examples/CollapseHorizontal.js
- src/Collapse.js
- src/__tests__/Collapse.spec.js
- types/lib/Collapse.d.ts
> Add horizontal collapse

- .github/workflows/test.yml
> chore(github-actions): add test.yml

- .github/workflows/coverage.yml
- README.md
- package.json
- yarn.lock
> GitHub actions coveralls

- CHANGELOG.md
- package.json
* **Dropdown:** add support for listbox or menu role ([#2077](https://github.com/reactstrap/reactstrap/issues/2077)) ([fd9e988](https://github.com/reactstrap/reactstrap/commit/fd9e9888b7712905a85684f7822fc75fde38c069))
> Release 8.10.0

- .github/workflows/docs.yml
- scripts/docs
> chore(github actions): manually publish docs

- scripts/docs
> chore(publish docs): don't silence output when pushing

- scripts/docs
> chore(publish docs): use GITHUB_TOKEN for auth

- scripts/docs
> chore(publish docs): Add back user config

- .github/workflows/docs.yml
> chore(publish docs): Add REACTSTRAP_DOCS_GITHUB_TOKEN

- .github/workflows/publish.yml
> chore(publish): update docs publishing

- types/lib/DropdownMenu.d.ts
- types/lib/Popover.d.ts
- types/lib/Tooltip.d.ts
> fix(types): use types from @popperjs/core

- types/lib/UncontrolledAccordion.d.ts
> fix(types): import React for UncontrolledAccordion type defs

- .github/workflows/coverage.yml
- .github/workflows/test.yml
- package.json
- src/Navbar.js
- src/__tests__/Navbar.spec.js
- src/utils.js
- stories/examples/Navbar.js
- types/lib/Navbar.d.ts
- yarn.lock
> feat(Navbar): add container options

- .storybook/preview.cjs
- src/Popover.js
- stories/examples/DropdownSetActiveFromChild.js
- stories/examples/Form/FormInline.js
- stories/examples/Navbar.js
- stories/examples/NavbarToggler.js
- stories/examples/PopoverMulti.js
- stories/examples/PopoverUncontrolled.js
- stories/examples/TooltipMulti.js
> fix(popover): add default popper offset for popover

- .storybook/manager-head.html
- .storybook/manager.cjs
> chore(docs): add custom favicon and title to storybook

- .github/workflows/tag_release.yml
- package.json
- scripts/release
- scripts/tag_release
> chore(github-actions): add workflow to tag releases

- .github/workflows/publish.yml
See https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
We don't want drafts/pre-release to trigger this event
> chore(publish): update publish workflow to run on release: released

- types/index.d.ts
> fix(types): export AccordionBody types

- package.json
microbundle defaults to --compress true, and apps should be minifying their own code
> fix(build): set --compress false for microbundle build

- package.json
> fix: add common js bundle to exports field

- .github/workflows/release-please.yml
- .github/workflows/test.yml
> chore: add release-* and remove bootstrap5 branch from test triggers

- .storybook/manager.cjs
- .storybook/preview.cjs
- stories/GitHub.stories.mdx
Logo links to GitHub
Add Sidebar section with links
Fixes #2369
> docs: add GitHub links to storybook

- src/Row.js
- src/__tests__/Row.spec.js
- stories/examples/Form/FormGridFormRow.js
- types/lib/Row.d.ts
- types/reactstrap-tests.tsx
`form-row` was removed from Bootstrap, breaking `<Form row>`. This change removes the option.
> `form-row` was removed in Bootstrap 5.

- src/AccordionBody.js
> fix(docs): fixed naming in Accordion module

- src/UncontrolledAccordion.js
- stories/examples/AccordionFlush.js
- stories/examples/AccordionProps.js
> fix(Accordion): fix incorrect props for accordion

- src/CarouselIndicators.js
> fix(#2393): captions visible twice

- src/Label.js
- src/__tests__/Label.spec.js
> fix(#2521): fix `form-check-label`/`form-label` class on Label

- src/Button.js
- src/__tests__/Button.spec.js
> convert button to use hooks

- src/Modal.js
> fix(#2411): remove scroll from body when modal open

- src/Spinner.js
- stories/Spinner.stories.js
- stories/examples/SpinnerAlignment.js
- stories/examples/SpinnerButton.js
- stories/examples/SpinnerColors.js
- stories/examples/SpinnerCustomSize.js
- stories/examples/SpinnerGrower.js
- stories/examples/SpinnerSize.js
Add new examples
Add description to props
> docs(Spinner): update Spinner docs to follow Bootstrap documentaion

- src/Carousel.js
- stories/Carousel.stories.js
- stories/examples/Carousel.js
> fix(#2555): Add crossfade to Carousel

- stories/Accordion.stories.js
- stories/Alert.stories.js
- stories/Badge.stories.js
- stories/Breadcrumb.stories.js
- stories/Button.stories.js
- stories/Card.stories.js
- stories/CloseButton.stories.js
- stories/Collapse.stories.js
- stories/Dropdown.stories.js
- stories/Fade.stories.js
- stories/Forms.stories.js
- stories/InputGroup.stories.js
- stories/Layout.stories.js
- stories/List.stories.js
- stories/ListGroup.stories.js
- stories/Modal.stories.js
- stories/Nav.stories.js
- stories/Navbar.stories.js
- stories/Offcanvas.stories.js
- stories/Pagination.stories.js
- stories/Placeholder.stories.js
- stories/Popover.stories.js
- stories/Progress.stories.js
- stories/Spinner.stories.js
- stories/Table.stories.js
- stories/Toast.stories.js
- stories/Tooltip.stories.js
> Chores(#2559): Removed unused react import from stories

- stories/examples/Alert/Alert.js
> docs(Alert): remove incorrect prop in example

- .eslintrc.json
- package.json
- src/__tests__/Accordion.spec.js
- src/__tests__/AccordionBody.spec.js
- src/__tests__/AccordionHeader.spec.js
- src/__tests__/AccordionItem.spec.js
- src/__tests__/UncontrolledAccordion.spec.js
- src/testUtils.js
- yarn.lock
> Migrate to react testing library

- src/Dropdown.js
fix key prop warning for dropdown when used within an  InputGroup
> fix(#2593): fix key prop warning for dropdown

- stories/Forms.stories.js
- stories/examples/Form/Switches.js
- stories/examples/Form/SwitchesExample.js
> docs(#2587): add switch to docs

- src/__tests__/Badge.spec.js
- src/__tests__/Breadcrumb.spec.js
- src/__tests__/BreadcrumbList.spec.js
- src/__tests__/Button.spec.js
- src/__tests__/ButtonGroup.spec.js
- src/__tests__/ButtonToggle.spec.js
- src/__tests__/ButtonToolbar.spec.js
- src/__tests__/Card.spec.js
- src/__tests__/CardBody.spec.js
- src/__tests__/CardColumns.spec.js
- src/__tests__/CardDeck.spec.js
- src/__tests__/CardFooter.spec.js
- src/__tests__/CardGroup.spec.js
- src/__tests__/CardHeader.spec.js
- src/__tests__/CardImg.spec.js
- src/__tests__/CardImgOverlay.spec.js
- src/__tests__/CardLink.spec.js
- src/__tests__/CardSubtitle.spec.js
- src/__tests__/CardText.spec.js
- src/__tests__/CardTitle.spec.js
- src/testUtils.js
> Migrate tests to rtl

- src/Carousel.js
- src/CarouselControl.js
- src/CarouselIndicators.js
- src/CarouselItem.js
- src/__tests__/Carousel.spec.js
- src/__tests__/UncontrolledCarousel.spec.js
> Fix carousel (#2421) and add migrate tests to RTL

- src/Dropdown.js
> fix(#2467): keyboard support for dropdown listbox

- stories/Index.stories.mdx
> docs(#2607): add docs on css module

- src/__tests__/CloseButton.spec.js
- src/__tests__/Col.spec.js
- src/__tests__/Collapse.spec.js
- src/__tests__/Container.spec.js
- src/__tests__/Modal.spec.js
- src/__tests__/Offcanvas.spec.js
- src/utils.js
> Migrate to rtl 2

- src/__tests__/ButtonDropdown.spec.js
- src/__tests__/Fade.spec.js
- src/__tests__/Form.spec.js
- src/__tests__/FormFeedback.spec.js
- src/__tests__/Row.spec.js
- src/__tests__/Spinner.spec.js
> Migrate to React Testing Library (#2625)

- src/__tests__/Toast.spec.js
- src/testUtils.js
> test(#2625): migrate tests for Toast to rtl

- types/lib/Accordion.d.ts
> fix(accordion): type error of open in uncontrolledAccordionProps

- src/Dropdown.js
- src/__tests__/Dropdown.spec.js
- src/__tests__/ToastHeader.spec.js
> Migrate to RTL (Dropdown, ToastHeader)

- src/__tests__/Label.spec.js
> fix(Label): migrate label to rtl

- src/Placeholder.js
- src/__tests__/Placeholder.spec.js
> Migrate placeholder to rtl

- src/__tests__/Navbar.spec.js
> Chore (Navbar): migrate to RTL

- src/__tests__/ModalBody.spec.js
- src/__tests__/ModalFooter.spec.js
- src/__tests__/ModalHeader.spec.js
- migrate ModalHeader
- migrate ModalFooter
- migrate ModalBody
> chore: migrate to rtl

- src/__tests__/Table.spec.js
> Chore (Table): migrate to RTL

- src/__tests__/ToastBody.spec.js
> Chore (ToastBody) migrate to RTL

- src/__tests__/OffcanvasBody.spec.js
- src/__tests__/OffcanvasHeader.spec.js
-migrate OffcanvasHeader
-migrate OffcanvasBody
> Chore (Offcanvas) migrate to RTL

- package.json
> fix: esm and lib folder not included in release

- src/__tests__/Modal.spec.js
> fix: properly provide `isOpen` in a modal's test

- babel.esm.config.cjs
> fix(#2427): error building esm files

- README.md
ArcGIS bases it's UI library (jimu-ui) on reactstrap in their new Experience Builder product. Developers adding custom widgets to the map experience use and extend this library.
> docs(readme): add ArcGIS jimu-ui to in the wild section

- src/Offcanvas.js
Replace callback refs with React.createRef() and update to access ref.current
> fix(reactstrap#2742): Replace callback refs with React.createRef()

- src/__tests__/Dropdown.spec.js
- src/__tests__/DropdownToggle.spec.js
- src/__tests__/InputGroup.spec.js
- src/__tests__/NavItem.spec.js
- src/__tests__/NavbarText.spec.js
- src/__tests__/NavbarToggler.spec.js
- src/__tests__/Placeholder.spec.js
- src/__tests__/Popover.spec.js
- src/__tests__/PopperContent.spec.js
- src/__tests__/Tooltip.spec.js
- NavbarText
- NavbarToggler
- NavItem
- Popover
- PopperContent
- Tooltip
> chore: migrate tests to RTL

- src/Offcanvas.js
- stories/Offcanvas.stories.js
- stories/examples/Offcanvas/Offcanvas.js
- stories/examples/Offcanvas/OffcanvasExample.js
- stories/examples/Offcanvas/OffcanvasProps.js
> fix(#2755): make offcanvas example code readable

- src/Popover.js
- src/Tooltip.js
- src/__tests__/Popover.spec.js
- src/__tests__/Tooltip.spec.js
> fix(#1680): arrowClass not applied to arrow

- src/Dropdown.js
- src/DropdownToggle.js
> Fixed Dropdown with inNavbar bug

- src/Dropdown.js
- src/DropdownToggle.js
This commit is for the release notes and the actual fix here is for linting
> fix: dropdown with inNavbar bug

- src/Fade.js
- src/Tooltip.js
- src/__tests__/utils.spec.js
- src/utils.js
chore(fixes #2801): use function default parameters instead of **defaultProps**
> chore(fixes #2801): use function default parameters
